<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Lecture-AI_programming/week02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Unboxed type
-  할당된 메모리 bit들이 해당 numeric data type의 특정 값을 표현하는데 다 사용되고 해당 type이 고유의 meta data나 method등을 가지고 있지 않음

### Boxed type
- 값을 저장하는 메모리 bit 이외에
- 가지고 있는 값에 대한 meta data
- meta data를 처리할 수 있는 method 가지고 있음.

<br>
<br>
https://dsaint31.tistory.com/456



In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

# 사용하고 있는 프레임워크의 버전을 남겨놓는 것은 좋은 습관.

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


# Tensor 간 변환
## From list(built-in) to tensor (numpy, tf, torch)

In [ ]:
ori = [1,2,3,4]
a_np = np.array(ori)
a_torch = torch.tensor(ori)
a_tf = tf.constant(ori)

print(a_np)
print(a_torch)
print(a_tf)

[1 2 3 4]
tensor([1, 2, 3, 4])
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
t = (1,2,3,4)

a_np = np.array(t)
a_torch = torch.tensor(t)
a_tf = tf.constant(t)

print(a_np)
print(a_torch)
print(a_tf)

[1 2 3 4]
tensor([1, 2, 3, 4])
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
print(a_np.__repr__())
print(a_np.__str__())
print((7.0).__repr__())
print(dir(7.0))

array([1, 2, 3, 4])
[1 2 3 4]
7.0
['__abs__', '__add__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getformat__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__le__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__pos__', '__pow__', '__radd__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmod__', '__rmul__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__setformat__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', 'as_integer_ratio', 'conjugate', 'fromhex', 'hex', 'imag', 'is_integer', 'real']


## From tensor(tf, torch) to ndarray(numpy)
- torch를 통해 얻은 ndarray 인스턴스는 원래의 tensor와 연결된 상태.
- 한 쪽에서 data 변경이 있을 경우 다른 쪽에도 영향을 줌. --> device="cpu" 한정

In [ ]:
# torch

b_np = a_torch.numpy()
print(b_np)

b_np[2] = 777
print(b_np)
print(a_torch) # b_np에서 바꾼 값이 a_torch에도 영향.

a_torch[3] = 888
print(b_np) # a_torch에서 바꾼 값이 b_np에도 영향.

[1 2 3 4]
[  1   2 777   4]
tensor([  1,   2, 777,   4])
[  1   2 777 888]


In [ ]:
a_torch = torch.tensor(t)
print(a_torch)
a_copy = a_torch.numpy().copy()
a_copy[0] = 999
print(a_copy)
print(a_torch)

tensor([1, 2, 3, 4])
[999   2   3   4]
tensor([1, 2, 3, 4])


In [ ]:
# tensorflow

b_np = a_tf.numpy()
print(b_np)

b_np[2] = 777
print(b_np)
print(a_tf) # b_np에서 바꾼 값이 a_tf에 영향을 주지 않음.

[1 2 3 4]
[  1   2 777   4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


## From ndarray to tensor
- numpy로 생성된 ndarray를 tensor로 옮기면 값을 바꿨을 때 numpy array는 값이 변경되지 않음.

In [ ]:
t = (1,2,3,4)

a_np = np.array(t)
a_torch = torch.tensor(a_np)
b_torch = torch.from_numpy(a_np)
a_tf = tf.constant(a_np)
b_tf = tf.convert_to_tensor(a_np)

print(a_np)
print(a_torch)
print(b_torch)
print(a_tf)
print(b_tf)

[1 2 3 4]
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
a_torch[2] = 777
print(a_torch)
print(a_np) # torch.tensor로 얻은 a_torch의 값을 바꿔도 a_np에 영향 없음.

b_torch[2] = 777
print(b_torch)
print(a_np) # torch.from_numpy로 얻은 a_torch의 값을 바꾸면 a_np에 영향.

tensor([  1,   2, 777,   4])
[1 2 3 4]
tensor([  1,   2, 777,   4])
[  1   2 777   4]


In [ ]:
# np 값 변환 후 torch 확인.
a_np = np.array(t) # 초기화
print(a_np)
a_np[2] = 777
print(a_np)
print(a_torch)
print(b_torch) # 얻은 방식과 상관없이 a_np의 값을 바꿔도 tf에는 영향 없음.

[1 2 3 4]
[  1   2 777   4]
tensor([  1,   2, 777,   4])
tensor([  1,   2, 777,   4])


In [ ]:
# tf값 변환 후 np 확인

print(a_tf)
a_tf = tf.tensor_scatter_nd_update(a_tf, tf.constant([[2]]), tf.constant([[777]]))
print(a_tf)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


InvalidArgumentError: cannot compute TensorScatterUpdate as input #2(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:TensorScatterUpdate] name: 

In [ ]:
a_np[2] = 777
print(a_np)
print(a_tf)
print(b_tf) # 얻은 방식과 상관없이 a_np의 값을 바꿔도 tf에는 영향 없음.

[  1   2 777   4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


습관적으로 float32로 dtype을 변환.

# dtype, shape 변경

## dtype 변경
바꾸는 원본 tensor인스턴스를 기반으로 원하는 dtype로 구성된 새로운 tensor인스턴스가 생성됨 (연결되지 않음)

In [ ]:
# numpy

a = np.ones((3,3))
b = np.uint8(a)
c = a.astype('float32')
print(c)

print(id(a),a.dtype)
print(id(b),b.dtype)
print(id(c),c.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
135881498334128 float64
135876225909648 uint8
135876225909936 float32


In [ ]:
print(a_torch.dtype)
print(a_torch.to(dtype = torch.float32)) # to: dtype을 어딘가로 보냄.
print(a_torch.dtype)

torch.int64
tensor([1., 2., 3., 4.])
torch.int64


자기 자신은 그대로 있고 새로 만들어준다는 느낌.<br>
반환한 것을 출력. -> 새로 만들어서 출력<br>
반환x -> 내부에서 변경.

In [ ]:
ori = [3, 2, 1, 4]
print(sorted(ori))
ori = [3,2,1,4]
print(ori)
print(ori.sort()) # 내부적으로는 sort가 된 상태. 반환 값이 없기 때문에 None으로 출력됨. (삭제와 같음)
print(ori)

[1, 2, 3, 4]
[3, 2, 1, 4]
None
[1, 2, 3, 4]


In [ ]:
# pytorch

a_torch = torch.rand(3,4)
b_torch = a_torch.to(torch.uint8) # 보통 데이터를 gpu 또는 cpu로 옮길 때 사용. 형 변환이 필요하기 때문에 함께 쓰임.
c_torch = a_torch.type(torch.float64)

print(a_torch)
print(b_torch)
print(c_torch)
print()
print(id(a_torch), a_torch.dtype)
print(id(b_torch), b_torch.dtype)
print(id(c_torch), c_torch.dtype)

b_torch[0,1] = 9
c_torch[0,0] = 1000
print()
print(a_torch)
print(b_torch)
print(c_torch)

tensor([[0.5093, 0.8662, 0.4856, 0.8386],
        [0.8164, 0.1564, 0.6892, 0.4811],
        [0.3276, 0.8413, 0.3654, 0.6044]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([[0.5093, 0.8662, 0.4856, 0.8386],
        [0.8164, 0.1564, 0.6892, 0.4811],
        [0.3276, 0.8413, 0.3654, 0.6044]], dtype=torch.float64)

135876230685744 torch.float32
135876225985776 torch.uint8
135876095051952 torch.float64

tensor([[0.5093, 0.8662, 0.4856, 0.8386],
        [0.8164, 0.1564, 0.6892, 0.4811],
        [0.3276, 0.8413, 0.3654, 0.6044]])
tensor([[0, 9, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([[1.0000e+03, 8.6622e-01, 4.8556e-01, 8.3857e-01],
        [8.1640e-01, 1.5637e-01, 6.8922e-01, 4.8105e-01],
        [3.2765e-01, 8.4131e-01, 3.6541e-01, 6.0444e-01]], dtype=torch.float64)


In [ ]:
# tensorflow

a_tf = tf.random.uniform(shape=(3,4))
c_tf = tf.dtypes.cast(a_tf,tf.float64)
print(c_tf)
print(id(a_tf), a_tf.dtype)
print(id(c_tf), c_tf.dtype)

tf.Tensor(
[[0.20860517 0.63256061 0.29463625 0.15664852]
 [0.90784907 0.01899362 0.16536796 0.28680599]
 [0.56927335 0.41285229 0.85150659 0.43190277]], shape=(3, 4), dtype=float64)
135876231081024 <dtype: 'float32'>
135876231085600 <dtype: 'float64'>


## shape 변경
- shape는 tensor의 각 축의 크기를 나타내는 sequence type의 인스턴스임.
- 즉, tensor의 크기와 형태를 나타냄.
<br>

### numpy
- numpy.reshape(src_ndarray, desired_shape)
- numpy.array.reshape(desired_shape)

### pytorch
- torch.reshape(src_tensor, desired_shape)
- torch.tensor.reshape(desired_shape)

### tensorflow
- tensorflow.reshape(src_tensor, desired_shape)

메모리가 contiguous해야 view를 만들 수 있음. <br>
transpose는 행렬을 바꿔놓기 때문에
일정하게 쭉 올라가던 메모리에서 순서가 꼬이게 됨.
is_contiguous 사용하면 인접한지 확인할 수 있음.


In [ ]:
# numpy

a = np.arange(0,10,1) # [ s:e :step_size]
b = a.reshape((2,5))
print(a.shape,id(a))
print(b.shape,id(b))
c = np.reshape(a,(5,2))
print(c.shape,id(c))
c[0,0] = 1000
print(a)
print(b)
print(c)

(10,) 136772160408048
(2, 5) 136772013527312
(5, 2) 136772013524144
[1000    1    2    3    4    5    6    7    8    9]
[[1000    1    2    3    4]
 [   5    6    7    8    9]]
[[1000    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]]


In [ ]:
# pytorch

a_torch = torch.arange(0,10,1)
b_torch = a_torch.reshape((2,5))
print(a_torch.shape,id(a_torch))
print(b_torch.shape,id(b_torch))
c_torch = torch.reshape(a_torch,(5,2))
print(c_torch.shape,id(c_torch))
c_torch[0,0] = 1000

print(a_torch)
print(b_torch)
print(c_torch)

torch.Size([10]) 136772165436736
torch.Size([2, 5]) 136772012777904
torch.Size([5, 2]) 136772165954960
tensor([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[1000,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([[1000,    1],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])


In [ ]:
# tensorflow

a_tensor = tf.range(0,10,1)
b_tensor = tf.reshape(a_tensor,(2,5))
# b_tensor = a_tensor.reshape((2,5)) # not working
print(a_tensor.shape,id(a_tensor))
print(b_tensor.shape,id(b_tensor))

c_tensor = tf.reshape(a_tensor,(5,2))
print(c_tensor.shape,id(c_tensor))

# 변경하고 싶은 위치와 값을 정의
indices = tf.constant([[0, 0]]) # (2, 2) 위치를 변경하고자 함
updates = tf.constant([999]) # 해당 위치에 넣고 싶은 값

# 업데이트 적용
c_tensor = tf.tensor_scatter_nd_update(c_tensor, indices, updates)

print(a_tensor)
print(b_tensor)
print(c_tensor)

(10,) 136777747448048
(2, 5) 136772015015712
(5, 2) 136772015028384
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[999   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]], shape=(5, 2), dtype=int32)


# Indexing / Slicing

In [ ]:
a = np.arange(0, 12).reshape(3,4)

print(a)
print('===================')
print(f'a[0] is "{a[0]}"')
print(f'a[0, 2] is "{a[0, 2]}"')
print(f'a[0][2] is "{a[0][2]}"')
print('-------------------')
print(f'a[1, 2:] is "{a[1,2:]}"')
print(f'a[1, ::2] is "{a[1,::2]}"')
print(f'a[1, ::-2] is "{a[1,::-2]}"')
print(f'a[1, ::-1] is "{a[1,::-1]}"')
print(f'a[1, 3:0:-1] is "{a[1, 3:0:-1]}"')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a[0] is "[0 1 2 3]"
a[0, 2] is "2"
a[0][2] is "2"
-------------------
a[1, 2:] is "[6 7]"
a[1, ::2] is "[4 6]"
a[1, ::-2] is "[7 5]"
a[1, ::-1] is "[7 6 5 4]"
a[1, 3:0:-1] is "[7 6 5]"


In [ ]:
# pytorch

a = np.arange(0, 12).reshape(3,4)
a_torch = torch.tensor(a)

print(a_torch)
print('===================')
print(f'a_torch[0] is "{a_torch[0]}"')
print(f'a_torch[0, 2] is "{a_torch[0, 2]}"')
print(f'a_torch[0][2] is "{a_torch[0][2]}"')
print('-------------------')
print(f'a_torch[1, 2:] is "{a_torch[1,2:]}"')
print(f'a_torch[1, ::2] is "{a_torch[1,::2]}"')

# negative는 동작하지 않음.
# print(f'a_torch[1, ::-2] is "{a_torch[1,::-2]}"')
# print(f'a_torch[1, ::-1] is "{a_torch[1,::-1]}"')
# print(f'a_torch[1, 3:0:-1] is "{a_torch[1, 3:0:-1]}"')


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
a_torch[0] is "tensor([0, 1, 2, 3])"
a_torch[0, 2] is "2"
a_torch[0][2] is "2"
-------------------
a_torch[1, 2:] is "tensor([6, 7])"
a_torch[1, ::2] is "tensor([4, 6])"


In [ ]:
# tensorflow

a = np.arange(0, 12).reshape(3,4)
a_tf = tf.constant(a)

print(a_tf)
print('===================')
print(f'a_tf[0] is "{a_tf[0]}"')
print(f'a_tf[0, 2] is "{a_tf[0, 2]}"')
print(f'a_tf[0][2] is "{a_tf[0][2]}"')
print('-------------------')
print(f'a_tf[1, 2:] is "{a_tf[1,2:]}"')
print(f'a_tf[1, ::2] is "{a_tf[1,::2]}"')
print(f'a_tf[1, ::-2] is "{a_tf[1,::-2]}"')
print(f'a_tf[1, ::-1] is "{a_tf[1,::-1]}"')
print(f'a_tf[1, 3:0:-1] is "{a_tf[1, 3:0:-1]}"')

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int64)
a_tf[0] is "[0 1 2 3]"
a_tf[0, 2] is "2"
a_tf[0][2] is "2"
-------------------
a_tf[1, 2:] is "[6 7]"
a_tf[1, ::2] is "[4 6]"
a_tf[1, ::-2] is "[7 5]"
a_tf[1, ::-1] is "[7 6 5 4]"
a_tf[1, 3:0:-1] is "[7 6 5]"


## Fancy Indexing

In [ ]:
# 1d tensor

x = np.array([10.,20.,30.,40.,50.])
x_torch = torch.tensor([10.,20.,30.,40.,50.])
x_tf = tf.constant([10.,20.,30.,40.,50.])

f_indices = [3, 4, 1]

print('original:')
print(x)
print('----------')
print('numpy:')
print(x[f_indices])
print('----------')
print('torch:')
print(x_torch[f_indices])
print('----------')
print('tensorflow:')
print(tf.gather(x_tf,f_indices)) #1D 에선 gahter, 2D 이상시 gather_nd
print(tf.gather_nd(x_tf, [ i for i in zip(f_indices,)])) # 굳이 쓴다면, 다음과 같이.

original:
[10. 20. 30. 40. 50.]
----------
numpy:
[40. 50. 20.]
----------
torch:
tensor([40., 50., 20.])
----------
tensorflow:
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)
tf.Tensor([40. 50. 20.], shape=(3,), dtype=float32)


In [ ]:
# 2d tensor

x = np.arange(5*5).reshape(5,5) * 10
x_torch = torch.arange(5*5).view(size=(5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1, 2]
indices_1 = [0, 1, 2]

print('original:')
print(x)
print('----------')
print('numpy:')
b = x[indices_0, indices_1]
print('b.shape =',b.shape)
print(b)
print('----------')
print('torch:')
c = x_torch[indices_0, indices_1]
print('c.shape =',c.shape)
print(c)
print('----------')
print('tensorflow:')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1)])
print('d.shape =',d.shape)
print(d)

original:
[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]
 [200 210 220 230 240]]
----------
numpy:
b.shape = (3,)
[  0  60 120]
----------
torch:
c.shape = torch.Size([3])
tensor([  0,  60, 120])
----------
tensorflow:
d.shape = (3,)
tf.Tensor([  0  60 120], shape=(3,), dtype=int64)


In [ ]:
# 3d tensor

x = np.arange(5*5*5).reshape(5,5,5) * 10
x_torch = torch.arange(5*5*5).view(size=(5,5,5)) * 10
x_tf = tf.constant(x)

indices_0 = [0, 1] # x
indices_1 = [1, 2] # y
indices_2 = [2, 0] # z

print('original:')
print(x)
print('----------')
print('numpy:')
b = x[indices_0, indices_1, indices_2]
print('b.shape=',b.shape)
print(b)
print('----------')
print('torch:')
c = x_torch[indices_0, indices_1, indices_2]
print('c.shape=',c.shape)
print(c)
print('----------')
print('tensorflow')
d = tf.gather_nd(x_tf, [ i for i in zip(indices_0, indices_1, indices_2)]) # multi-dim 에선 gater_nd 임.
print('d.shape=',d.shape)
print(d)

original:
[[[   0   10   20   30   40]
  [  50   60   70   80   90]
  [ 100  110  120  130  140]
  [ 150  160  170  180  190]
  [ 200  210  220  230  240]]

 [[ 250  260  270  280  290]
  [ 300  310  320  330  340]
  [ 350  360  370  380  390]
  [ 400  410  420  430  440]
  [ 450  460  470  480  490]]

 [[ 500  510  520  530  540]
  [ 550  560  570  580  590]
  [ 600  610  620  630  640]
  [ 650  660  670  680  690]
  [ 700  710  720  730  740]]

 [[ 750  760  770  780  790]
  [ 800  810  820  830  840]
  [ 850  860  870  880  890]
  [ 900  910  920  930  940]
  [ 950  960  970  980  990]]

 [[1000 1010 1020 1030 1040]
  [1050 1060 1070 1080 1090]
  [1100 1110 1120 1130 1140]
  [1150 1160 1170 1180 1190]
  [1200 1210 1220 1230 1240]]]
----------
numpy:
b.shape= (2,)
[ 70 350]
----------
torch:
c.shape= torch.Size([2])
tensor([ 70, 350])
----------
tensorflow
d.shape= (2,)
tf.Tensor([ 70 350], shape=(2,), dtype=int64)


## Boolean Mask

In [ ]:
x = np.arange(3*3*3).reshape(3,3,3) * 10

print('original:')
print(x)
print('----------')
print('boolean mask:')
b = x <= 270/2
print(b.shape)
print(b)
print('----------')
print('x <= 135')
print(x[b])
print('----------')
print(x[x<=270/2])
print('----------')
print('----------')
print('x <= 135 | x>= 200')
b1 = b | (x >= 200)
print('----------')
print('boolean mask')
print(b1)
print('----------')
print(x[b1])
print('----------')
print(x[ (x<=270/2) | (x>=200)])

original:
[[[  0  10  20]
  [ 30  40  50]
  [ 60  70  80]]

 [[ 90 100 110]
  [120 130 140]
  [150 160 170]]

 [[180 190 200]
  [210 220 230]
  [240 250 260]]]
----------
boolean mask:
(3, 3, 3)
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False False]
  [False False False]
  [False False False]]]
----------
x <= 135
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130]
----------
----------
x <= 135 | x>= 200
----------
boolean mask
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True False]
  [False False False]]

 [[False False  True]
  [ True  True  True]
  [ True  True  True]]]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 240 250 260]
----------
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 200 210 220 230
 24

In [ ]:
x_torch = torch.arange(3*3*3).view(size=(3,3,3)) * 10
print(x_torch[ (x_torch<=270/2) | (x_torch>=200)])

print('--------------')

x_tf = tf.constant(x)
print(x_tf[ (x_tf<= tf.cast(270/2, tf.int64)) | (x_tf>=200)])

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        200, 210, 220, 230, 240, 250, 260])
--------------
tf.Tensor(
[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
  200  210  220  230  240  250  260  270  280  290  300  310  320  330
  340  350  360  370  380  390  400  410  420  430  440  450  460  470
  480  490  500  510  520  530  540  550  560  570  580  590  600  610
  620  630  640  650  660  670  680  690  700  710  720  730  740  750
  760  770  780  790  800  810  820  830  840  850  860  870  880  890
  900  910  920  930  940  950  960  970  980  990 1000 1010 1020 1030
 1040 1050 1060 1070 1080 1090 1100 1110 1120 1130 1140 1150 1160 1170
 1180 1190 1200 1210 1220 1230 1240], shape=(119,), dtype=int64)


**특정 조건에 맞는 element의 index 얻기: np.where**

In [ ]:
import numpy as np

r = np.random.default_rng(seed = 23)

a = r.random((3,3,3)).astype(np.float32) * 10.

bm = a>=5.
idxs = np.where( a>=5)

print(a)
print('-----------------')
print(np.array(idxs).shape)
print(idxs)

[[[6.9393306  6.4145823  1.2864423 ]
  [1.1370804  6.5334554  8.534571  ]
  [2.0177913  2.1801863  7.1658463 ]]

 [[4.706997   4.1522193  3.491478  ]
  [0.6385375  4.546662   3.014533  ]
  [3.8907673  5.402978   6.835897  ]]

 [[6.2475243  7.4270444  0.18217355]
  [6.542572   5.420625   8.513411  ]
  [9.390292   0.12823118 8.283283  ]]]
-----------------
(3, 14)
(array([0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 2]), array([0, 0, 1, 1, 2, 2, 2, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 1, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 2]))


In [ ]:
a = np.arange(0,6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [ ]:
b = a < 3
b

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
a[b]

array([0, 1, 2])

In [ ]:
c = a[a<3]
c

array([0, 1, 2])

In [ ]:
i = np.where(a<3)
i

(array([0, 0, 0]), array([0, 1, 2]))

In [ ]:
a[np.where(a<3)]

array([0, 1, 2])

In [ ]:
a[a<3]=0
a

array([[0, 0, 0],
       [3, 4, 5]])

## vectorized operation
- vector or matrix 전체에 대해 동일한 연산을 동시에 수행하는 방식.

In [ ]:
# ex1.

print("for loop")
def add_vectors(x, y):
  """두 벡터를 더합니다."""
  result = []
  for i in range(len(x)):
    result.append(x[i] + y[i])
  return result

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = add_vectors(x, y)

print(z)

print("vector op.")
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = np.add(x, y)  # 벡터 덧셈

print(z)
# [5 7 9]


for loop
[5, 7, 9]
vector op.
[5 7 9]


### Aggregations

2x3에서 2x1로 만들었다고 할 때 평균을 어떻게 낼 것인가?


옵션이 0이면 1x3으로,
옵션이 1이면 2x1로.


## Broadcasting

leading side - 왼쪽으로.
