In [ ]:
import numpy as np
import tensorflow as tf
import torch

### 버전 확인

In [ ]:
np.__version__

'1.25.2'

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
torch.__version__

'2.2.1+cu121'

In [ ]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]


### 크기 / 차원 / 타입 확인
- ndim: dimension 개수
- shape: 몇 행, 몇 열인지 반환
- itemsize: 차지하는 byte 수
- size: 전체 원소의 개수
- dtype: data type

data type에서 (6)과 (6,)은 매우 다른 것임. <br>
(6)은 integer, (6,)은 튜플.

In [ ]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [ ]:
print(a.ndim)
print(a.shape)
print(a.itemsize) # byte 수
print(a.size)
print(a.dtype)

1
(6,)
8
6
int64


In [ ]:
a = np.array([1.,2.,3.])
print(a.dtype)
a = np.array([1.,2.,3.], dtype=int)
print(a.dtype)
a = np.array([1.,2.,3.], dtype=float)
print(a.dtype)

float64
int64
float64


In [ ]:
# tensoflow에서 tensor 생성
# tensorflow는 gpu기반 연산이기 때문에 int32와 float32를 사용.
tensor = tf.constant(t)
print(tf.rank(tensor)) # dimension 수 반환.
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int32'>


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
# torch에서 tensor 생성
p = torch.tensor(t)
print(p.ndim, type(p.ndim))
print(p.shape, type(p.shape))
print(p.itemsize, type(p.itemsize))
print(p.size, type(p.size()))
print(p.dtype, type(p.dtype))

1 <class 'int'>
torch.Size([6]) <class 'torch.Size'>
8 <class 'int'>
<built-in method size of Tensor object at 0x796f81735710> <class 'torch.Size'>
torch.int64 <class 'torch.dtype'>


### dtype
- numpy: float64 / int64
- tensorflow: float32 / int32
- torch: float32 / int64

In [ ]:
# 이건 기억을 해놓자
print(np.array([1.,2.,3.]).dtype)
print(np.array([1,2,3]).dtype)
print(tf.constant([1.,2.,3.]).dtype)
print(tf.constant([1,2,3]).dtype)
print(torch.tensor([1.,2.,3.]).dtype)
print(torch.tensor([1,2,3]).dtype)

float64
int64
<dtype: 'float32'>
<dtype: 'int32'>
torch.float32
torch.int64


In [ ]:
# nested lists result in multi-dimensional arrays
a = np.array([range(i, i+3) for i in [2,4,6]]) # comprehension
print(a.ndim)
print(a.shape)
print(a.itemsize) # byte 수
print(a.size)
print(a.dtype)
a

2
(3, 3)
8
9
int64


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.dtype)
tensor

tf.Tensor(2, shape=(), dtype=int32)
2
<dtype: 'int64'>


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])>

### zeros
- 행렬을 0으로 채움

In [ ]:
a = np.zeros((3,2))
print(a.dtype)
a

float64


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a_tf = tf.zeros(shape=(3,2))
print(a_tf.dtype)
a_tf

<dtype: 'float32'>


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a_tf.numpy()

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

### ones
- 행렬을 1로 채움

In [ ]:
a = np.ones((3,2))
print(a.dtype)
a

float64


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### full / fill
- 행렬을 특정 값으로 가득 채움

In [ ]:
a = np.full((1,3),255)
print(a.dtype)
a

int64


array([[255, 255, 255]])

In [ ]:
a_tf = tf.fill((1,3),255)
print(a_tf.dtype)
a_tf

<dtype: 'int32'>


<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[255, 255, 255]], dtype=int32)>

### 원하는 값으로 행렬 채우기
- arange: 시작과 끝값을 설정하고 특정 값이 계속 더해지는 1차원 벡터 생성
- linspace: 시작과 끝값을 설정하고 특정 값으로 등분하는 1차원 벡터 샐성
- empty: 빈 값으로 행렬 생성
- eye: identity matrix 생성

In [ ]:
print(range(0,10,1))
print(np.arange(0, 1, 0.1))

range(0, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a = np.arange(0,24,2).reshape(3,4)
print(a.dtype)
a

int64


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a = np.linspace(1,5,6) # (시작, 끝, 등분)
print(a.dtype)
print(a)
a_tf = tf.linspace(1,5,6) # float32가 아닌 float64임을 주의.
print(a_tf.dtype)
b_tf = tf.dtypes.cast(a_tf, tf.float32) # 바꿔서 casting해주는 것이 좋음.
print(b_tf.dtype)
print(b_tf)
a_torch = torch.linspace(1,5,6)
print(a_torch.dtype)
print(a_torch)

float64
[1.  1.8 2.6 3.4 4.2 5. ]
<dtype: 'float64'>
<dtype: 'float32'>
tf.Tensor([1.  1.8 2.6 3.4 4.2 5. ], shape=(6,), dtype=float32)
torch.float32
tensor([1.0000, 1.8000, 2.6000, 3.4000, 4.2000, 5.0000])


In [ ]:
a = np.empty((4,2)) # 초기화를 안 하기 때문에 빠름.
print(a.dtype)
print(a)
a_torch = torch.empty((4,2))
print(a_torch.dtype)
print(a_torch)


float64
[[4.86809279e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
torch.float32
tensor([[-5.4627e+09,  4.3564e-41],
        [-7.8106e-37,  3.2140e-41],
        [ 4.2000e+00,  5.0000e+00],
        [ 1.8077e-43,  0.0000e+00]])


In [ ]:
xxx = np.eye(3) # identity matrix
print(xxx)
xxx

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 파이썬 자료형
### Immutable
- 불변형 자료형.
- 값을 바꿀 때 메모리에 저장된 데이터를 없애고 만듦.
- int, float, str, tuple

### Mutable
- 변형 자료형.
- 값을 바꿀 때 할당된 메모리를 놔두고 내용만 바꿈.
- list, dict

<br>

### collection
- 데이터를 서로 연관시키지 않고 모아두는 컨테이너.
- set, dict 등.
  - set: 반복 가능, mutable, 중복x, 정렬x

### sequence
- 순서가 유지되고 정수로 인덱싱하며 길이가 있는 컨테이너.
- str(character의 시퀀스), list, tuple, 사용자 정의 클래스

### mapping
- key와 value의 짝으로 이루어짐.
- dict.
