<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Lecture-AI_programming/week07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week07
(중간고사 review)

In [ ]:
import numpy as np
import tensorflow as tf
import torch

## inplace operation
원래 있던 것에서 update하는 방식
- 계산 전 값이 필요하지 않을 때 사용.
- 추가 메모리 할당 없이 기존 할당된 메모리를 그대로 사용함.
- 함수 뒤에 언더바(`_`)를 붙임. ex) `add_()`, `scatter_()` 등.
- `+=`, `*=` 등도 inplace operation.


In [ ]:
a = torch.arange(6)
a.random_()
print(a)

tensor([4951360797863611809, 2585332681438799044, 2428829233476408226,
        3355125140765155757, 7212651704529322310, 6140720535927486135])


## `reshape()` vs. `resize()`
- `reshape()`는 바꾸고자 하는 shape의 원소의 개수가 다르면 오류가 나지만 `resize()`는 자동으로 맞춰줌.
- 빈 곳(안 맞는 곳)은 처음부터 반복하는 형식으로 맞춰줌.
- resize는 in-place

In [ ]:
a = torch.tensor([[0.6060, 0.1140, 0.0921],
                  [0.1477, 0.4904, 0.7813]])
print(torch.where(a > .5))

(tensor([0, 1]), tensor([0, 2]))


## `__repr__()`, `__str__()`
`__repr__()`은 값과 함께 타입을 보여줌. 개발자용. 문자열로 반환.
<br>`__str__()`은 값이 중요.

In [ ]:
torch.where(a > .5).__repr__()

'(tensor([0, 1]), tensor([0, 2]))'

In [ ]:
torch.where(a > .5)

(tensor([0, 1]), tensor([0, 2]))

In [ ]:
a = torch.arange(6).reshape((2,3))
print(a)
print(torch.where(a > 2))

tensor([[0, 1, 2],
        [3, 4, 5]])
(tensor([1, 1, 1]), tensor([0, 1, 2]))


## list vs. ndarray vs. tensor
### list
- 하나의 리스트에 모든 데이터 타입이 전부 들어갈 수 있음. -> 불균형하게 들어갈 수 있음.
- boxed type

### ndarray
- c, c++에서의 어레이.
- 데이터가 모두 연결.
- 효율적.
- 자료형을 바꾸려면 새로 만들어야 함
- 주로 cpu와 ram에서 동작하는 것 위주로.
- cpu 기반 병렬 처리

### tensor
- gpu 기반
- cpu에서 썼을 때는 numpy가 훨씬 빠름.

## `detach()` vs. `clone()`

### `detach()`
- 복사 대상 tensor와 memory 공유. -> 기존값이 변하면 복사된 값도 변함.
- 기울기 계산 그래프에서 제외됨.

### `clone()`
- 모든 정보 copy, 새로운 메모리 할당.
- 연산 정보를 동시에 가지고 있음.
- in-place operation error 피할 수 있음.

pytorch에서는 기울기가 계산되는 leaf node(requires_grad=True)에 대해서는 in-place operation이 금지되어 있음.

## hook
- 패키지를 만드는 코드에서 중간에 원하는 코드를 삽입할 수 있는 기능.
- 순전파 이후 모델의 가중치를 변경하거나 파라미터 업데이트를 실시간으로 확인하는 등 바꾸고 싶은 모델을 변형하여 사용할 수 있음.

