<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Lecture-AI_programming/week07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week07
(중간고사 review)

In [1]:
import numpy as np
import tensorflow as tf
import torch

### inplace operation
원래 있던 것에서 update하는 방식



reshape() vs. resize()

In [2]:
a = torch.arange(6)
a.random_()
print(a)

tensor([4951360797863611809, 2585332681438799044, 2428829233476408226,
        3355125140765155757, 7212651704529322310, 6140720535927486135])


In [3]:
a = torch.tensor([[0.6060, 0.1140, 0.0921],
                  [0.1477, 0.4904, 0.7813]])
print(torch.where(a > .5))

(tensor([0, 1]), tensor([0, 2]))


In [6]:
torch.where(a > .5).__repr__()

'(tensor([0, 1]), tensor([0, 2]))'

In [4]:
torch.where(a > .5)

(tensor([0, 1]), tensor([0, 2]))

In [9]:
a = torch.arange(6).reshape((2,3))
print(a)
print(torch.where(a > 2))

tensor([[0, 1, 2],
        [3, 4, 5]])
(tensor([1, 1, 1]), tensor([0, 1, 2]))


`__repr__()`은 값과 함께 타입을 보여줌. 개발자용. 문자열로 반환.
<br>`__str__`()은 값이 중요.

list vs. ndarray vs. tensor
list
: 하나의 리스트에 모든 데이터 타입이 전부 들어갈 수 있음. -> 불균형하게 들어갈 수 있음.
boxed type

ndarray
c, c++에서의 어레이.
데이터가 모두 연결.
효율적.
자료형을 바꾸려면 새로 만들어야 함
주로 cpu와 ram에서 동작하는 것 위주로.
cpu 기반 병렬 처리

tensor.
gpu 기반
cpu에서 썼을 때는 numpy가 훨씬 빠름.

detach() vs. clone()

clone()
모든 정보 copy.
연산 정보를 동시에 가지고 있음.

hook 한 번 찾아보기
