<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import torch
import numpy as np
import tensorflow as tf

# 코드 작성

주어진 Python 튜플을 이용해 NumPy 배열을 생성하고, 배열의 차원(dimension)과 형태(shape)를 출력하는 코드를 작성하시오.<br>
```t = (1, 2, 3, 4, 5, 6)```


In [5]:
t = (1, 2, 3, 4, 5, 6)
a_np = np.array(t)
print(a_np.ndim)
print(a_np.shape)

1
(6,)


주어진 PyTorch 텐서의 데이터 타입을 float32로 변환하고, 결과 텐서의 데이터 타입을 출력하는 코드를 작성하시오.
```
import torch
p = torch.tensor([1, 2, 3])
```

In [28]:
p = torch.FloatTensor([1,2,3])
print(p.dtype)

p_float = p.float()
print(p_float.dtype)

p = torch.tensor([1,2,3], dtype=torch.float32)
print(p.dtype)

torch.float32
torch.float32
torch.float32


2x3 배열을 생성하되, 첫 번째 행은 1부터 3까지 연속된 숫자로, 두 번째 행은 6부터 8까지 연속된 숫자로 채워진 NumPy 배열을 생성하고 출력하세요.



In [14]:
a = np.array([[1, 2, 3], [6, 7, 8]])
print(a)

[[1 2 3]
 [6 7 8]]


주어진 PyTorch 텐서에 대해 모든 요소의 합을 구하고, 결과를 출력하세요.
```
import torch
p = torch.tensor([[1, 2, 3], [4, 5, 6]])
```


In [27]:
p = torch.arange(1,7,1).reshape(2,3)
print(p.sum())
print(torch.sum(p))

tensor(21)
tensor(21)


# 결과 예측

아래 코드를 실행했을 때의 출력 결과를 예측하시오.
```
import numpy as np
a = np.array([1., 2., 3.])
print(a.dtype)
```

- float64

아래 코드를 실행했을 때의 출력 결과를 예측하시오.
```
import torch
p = torch.tensor([1, 2, 3])
p[1] = 777
print(p)
```

- tensor([1, 777, 3])

아래 코드를 실행했을 때의 출력 결과를 예측하세요.
```
import tensorflow as tf
a_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
print(a_tf.shape)
```

- (2, 3)

아래 코드를 실행했을 때의 출력 결과를 예측하세요.
```
import numpy as np
a = np.arange(5, 15, 2).reshape(2, 3)
print(a)
```

- [[5 7 9],<br>
[11 13 15]]


# 빈칸 채우기

주어진 PyTorch 텐서의 차원 수를 출력하는 코드의 빈칸을 채우시오.
```
import torch
p = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(p._____)
```

- ndim

아래 코드의 빈칸을 채워 TensorFlow 상수 텐서를 생성하고, 텐서의 데이터 타입을 출력하세요.
```
import tensorflow as tf
a_tf = tf.constant([1.0, 2.0, 3.0], dtype=tf._____)
print(a_tf.dtype)
```

- float32

아래 코드의 빈칸을 채워, 4x4 단위 행렬(identity matrix)을 생성하고 출력하세요.
```
import numpy as np
a = np._____(4)
print(a)
```

- eye

# tensor 간 변환
## 코드 작성


주어진 튜플 t = (5, 6, 7, 8)을 사용하여 numpy 배열, PyTorch 텐서, TensorFlow 텐서를 생성하는 코드를 작성하세요.

In [33]:
t = (5,6,7,8)
t_np = np.array(t)
t_torch = torch.tensor(t)
t_tf = tf.constant(t)

print(t_np)
print(t_torch)
print(t_tf)

[5 6 7 8]
tensor([5, 6, 7, 8])
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)


PyTorch 텐서 a_torch가 주어졌을 때, 이를 TensorFlow 텐서로 변환하는 코드를 작성하세요.<br>
```a_torch = torch.tensor([10, 20, 30, 40])```

In [35]:
a_torch = torch.tensor([10, 20, 30, 40])
a_tf = tf.constant(a_torch)
print(a_tf)

tf.Tensor([10 20 30 40], shape=(4,), dtype=int64)


Numpy 배열 a_np가 주어졌을 때, 배열 내 값이 50 이상인 모든 요소를 0으로 변경하는 코드를 작성하세요.<br>
```a_np = np.array([45, 55, 60, 40, 20, 80])```

In [37]:
a_np = np.array([45, 55, 60, 40, 20, 80])
a_np[a_np > 50] = 0
a_np

array([45,  0,  0, 40, 20,  0])

Numpy 배열 a_np를 생성하고, 이 배열을 사용하여 동일한 데이터를 가지지만 서로 다른 라이브러리(TensorFlow, PyTorch)의 Tensor 객체를 생성하는 코드를 작성하세요.<br>
```a_np = np.array([5, 10, 15, 20])```

In [39]:
a_np = np.array([5, 10, 15, 20])
a_tf = tf.convert_to_tensor(a_np)
a_torch = torch.from_numpy(a_np)
print(a_tf, type(a_tf))
print(a_torch, type(a_torch))

tf.Tensor([ 5 10 15 20], shape=(4,), dtype=int64) <class 'tensorflow.python.framework.ops.EagerTensor'>
tensor([ 5, 10, 15, 20]) <class 'torch.Tensor'>


## 결과 예측

다음 코드를 실행한 후의 a_np의 출력값은 무엇일까요? **(다시 풀기)**
```
t = (1, 2, 3, 4)
a_np = np.array(t)
a_torch = torch.tensor(a_np)
a_torch[2] = 777

print(a_np)
```

- [1 2 777 4]

다음 코드를 실행한 후 b_np의 출력값은?
```
t = (1, 2, 3, 4)
a_tf = tf.constant(t)
b_np = a_tf.numpy()
b_np[2] = 777

print(b_np)
```

- [1 2 777 4]

다음 코드를 실행한 후 a_torch와 b_torch의 출력값은?
```
t = (1, 2, 3, 4)
a_np = np.array(t)
b_torch = torch.from_numpy(a_np)
a_np[2] = 777

a_torch = torch.tensor(t)
print(a_torch)
print(b_torch)
```

- tensor([1, 2, 3, 4])<br>
tensor([1, 2, 777, 4])

다음 코드를 실행한 후, a_np, a_torch, b_torch의 결과를 예측하세요. **(다시 풀기)**

```
import numpy as np
import torch

t = (1, 2, 3, 4)
a_np = np.array(t)
a_torch = torch.tensor(a_np)
b_torch = torch.from_numpy(a_np)

b_torch[2] = 777
```

- a_np: [1 2 777 4] -> from_numpy()로 얻은 텐서를 조작했으므로
- a_torch: tensor([1, 2, 3, 4])
- b_torch: tensor([1, 2, 777, 4])

## 빈칸 채우기

다음 코드에서 빈칸에 들어갈 적절한 함수 또는 메서드 이름을 적으세요.

```
import numpy as np
import torch
import tensorflow as tf

# Tensor 생성
t = (1, 2, 3, 4)

a_np = np.array(t)
a_tf = tf.constant(t)
a_torch = torch.tensor(t)

# torch → numpy
b_np = a_torch.______()

```

- numpy

## 코드 수정하기

TensorFlow와 Numpy 간의 변환에서, 아래 코드는 오류 없이 실행되도록 수정해야 합니다. 수정해주세요.

```
import tensorflow as tf
import numpy as np

t = (1,2,3,4)

# 오류가 발생하는 부분
a_tf = tf.constant(t, dtype=tf.float64)
b_np = a_tf._______()  # a_tf를 Numpy 배열로 변환하는 코드

b_np[2] = 777

```

- numpy