<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Practice/tensor-dtype_shape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import tensorflow as tf

## dtype 변경

### PyTorch

다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 부동소수점으로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [5]:
import torch

# 주어진 텐서
a_torch = torch.tensor([1, 2, 3, 4])

# 주어진 텐서의 dtype을 부동소수점으로 변경하는 코드를 작성하세요.
a_torch = a_torch.to(torch.float32)
print(a_torch.dtype)

torch.float32


다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 64비트 정수로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [7]:
import torch

# 주어진 텐서
a_torch = torch.tensor([1.1, 2.2, 3.3, 4.4])

# 주어진 텐서의 dtype을 64비트 정수로 변경하는 코드를 작성하세요.
a_int = a_torch.type(torch.int64)
print(a_int)
print(a_int.dtype)

tensor([1, 2, 3, 4])
torch.int64


 다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 16비트 정수로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [8]:
import torch

# 주어진 텐서
a_torch = torch.tensor([0.5, 1.0, 1.5, 2.0])

# 주어진 텐서의 dtype을 16비트 정수로 변경하는 코드를 작성하세요.
a_int = a_int.to(torch.int16)
print(a_int)
print(a_int.dtype)

tensor([1, 2, 3, 4], dtype=torch.int16)
torch.int16


다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 부호 없는 8비트 정수로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [12]:
import torch

# 주어진 텐서
a_torch = torch.tensor([0.1, 0.2, 0.3, 0.4])

# 주어진 텐서의 dtype을 부호 없는 8비트 정수로 변경하는 코드를 작성하세요.
a_torch = a_torch.to(torch.uint8)
print(a_torch)
print(a_torch.dtype)

tensor([0, 0, 0, 0], dtype=torch.uint8)
torch.uint8


### NumPy
다음과 같은 NumPy 배열이 주어졌을 때, 이를 부호 없는 16비트 정수로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [13]:
import numpy as np

# 주어진 배열
a_np = np.array([5, 10, 15, 20])

# 주어진 배열의 dtype을 부호 없는 16비트 정수로 변경하는 코드를 작성하세요.
a_np = np.uint16(a_np)
print(a_np)
print(a_np.dtype)

[ 5 10 15 20]
uint16


다음과 같은 NumPy 배열이 주어졌을 때, 이를 부동소수점으로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [14]:
import numpy as np

# 주어진 배열
a_np = np.array([1, 2, 3, 4])

# 주어진 배열의 dtype을 부동소수점으로 변경하는 코드를 작성하세요.
a_np = a_np.astype('float32')
print(a_np)
print(a_np.dtype)

[1. 2. 3. 4.]
float32


## TensorFlow

다음과 같은 TensorFlow 텐서가 주어졌을 때, 이를 32비트 부동소수점으로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [15]:
import tensorflow as tf

# 주어진 텐서
a_tf = tf.constant([1.1, 2.2, 3.3, 4.4])

# 주어진 텐서의 dtype을 32비트 부동소수점으로 변경하는 코드를 작성하세요.
a_tf = tf.dtypes.cast(a_tf, tf.float32)
print(a_tf)
print(a_tf.dtype)

tf.Tensor([1.1 2.2 3.3 4.4], shape=(4,), dtype=float32)
<dtype: 'float32'>


다음과 같은 TensorFlow 텐서가 주어졌을 때, 이를 64비트 정수로 dtype을 변경하고 출력하는 코드를 작성하세요.

In [16]:
import tensorflow as tf

# 주어진 텐서
a_tf = tf.constant([5.0, 10.0, 15.0, 20.0])

# 주어진 텐서의 dtype을 64비트 정수로 변경하는 코드를 작성하세요.
a_tf = tf.dtypes.cast(a_tf, tf.int64)
print(a_tf)
print(a_tf.dtype)

tf.Tensor([ 5 10 15 20], shape=(4,), dtype=int64)
<dtype: 'int64'>


# Shape 변경

다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 2행 4열의 형태로 변경하고 출력하세요.

In [18]:
import torch

# 주어진 텐서
a_torch = torch.tensor([[1, 2, 3, 4],
                        [5, 6, 7, 8]])

# 주어진 텐서의 shape을 4행 2열로 변경하고 출력하는 코드를 작성하세요.
print(a_torch.reshape((4,2)))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 3차원 형태로 변경하고 출력하세요.

In [19]:
import torch

# 주어진 텐서
a_torch = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

# 주어진 텐서의 shape을 3차원으로 변경하고 출력하는 코드를 작성하세요.
t = torch.reshape(a_torch, (2,2,2))
print(t)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 2차원 형태로 변경하고 출력하세요.

In [20]:
import torch

# 주어진 텐서
a_torch = torch.arange(0, 6, 1)

# 주어진 텐서의 shape을 2차원으로 변경하고 출력하는 코드를 작성하세요.
t = a_torch.reshape((2, 3))
print(t)

tensor([[0, 1, 2],
        [3, 4, 5]])


다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 1차원 형태로 변경하고 출력하세요.

In [21]:
import torch

# 주어진 텐서
a_torch = torch.tensor([[1, 2, 3, 4]])

# 주어진 텐서의 shape을 1차원으로 변경하고 출력하는 코드를 작성하세요.
t1 = a_torch.squeeze()
t2 = a_torch.reshape((4))
print(t1)
print(t2)

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])


다음과 같은 PyTorch 텐서가 주어졌을 때, 이를 4행 2열의 형태로 변경하고 출력하세요.

In [22]:
import torch

# 주어진 텐서
a_torch = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

# 주어진 텐서의 shape을 4행 2열로 변경하고 출력하는 코드를 작성하세요.
t = torch.reshape(a_torch, (4, 2))
print(t)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


다음과 같은 NumPy 배열이 주어졌을 때, 이를 2행 3열의 형태로 변경하고 출력하세요.

In [24]:
import numpy as np

# 주어진 배열
a_np = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

# 주어진 배열의 shape을 2행 6열로 변경하고 출력하는 코드를 작성하세요.
t = a_np.reshape((2,6))
print(t)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


다음과 같은 NumPy 배열이 주어졌을 때, 이를 1차원 형태로 변경하고 출력하세요.

In [26]:
import numpy as np

# 주어진 배열
a_np = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# 주어진 배열의 shape을 1차원으로 변경하고 출력하는 코드를 작성하세요.
t1 = a_np.squeeze()
t2 = a_np.reshape((9))
print(t1)
print(t2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


다음과 같은 TensorFlow 텐서가 주어졌을 때, 이를 3차원 형태로 변경하고 출력하세요.

In [28]:
import tensorflow as tf

# 주어진 텐서
a_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])

# 주어진 텐서의 shape을 3차원으로 변경하고 출력하는 코드를 작성하세요.
t = tf.reshape(a_tf, (1, 2, 3))
print(t)
print(t.ndim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
3


다음과 같은 TensorFlow 텐서가 주어졌을 때, 이를 3차원 형태로 변경하고 출력하세요.

In [29]:
import tensorflow as tf

# 주어진 텐서
a_tf = tf.constant([1, 2, 3, 4, 5, 6])

# 주어진 텐서의 shape을 3차원으로 변경하고 출력하는 코드를 작성하세요.
t = tf.reshape(a_tf, (3, 2, 1))
print(t)
print(t.ndim)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]], shape=(3, 2, 1), dtype=int32)
3
