<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Practice/tensor-translation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import torch
import numpy as np
import tensorflow as tf

1. 주어진 NumPy 배열을 PyTorch 텐서로 변환하고, 변환된 텐서의 모양(shape)을 출력하세요.

In [ ]:
a = np.arange(0, 6, 1)
print(type(a))
a_t = torch.from_numpy(a)
print(a_t.dtype)
print(a_t.shape)

<class 'numpy.ndarray'>
torch.int64
torch.Size([6])


2. 주어진 PyTorch 텐서를 TensorFlow 텐서로 변환하고, 변환된 텐서의 데이터 타입(dtype)을 출력하세요.

In [ ]:
a_t = torch.tensor([1, 2, 3, 4])
a = np.array(a_t)
print(a.dtype)

int64


3. 주어진 TensorFlow 텐서를 NumPy 배열로 변환하고, 변환된 배열의 차원(dimension) 수(ndim)를 출력하세요.

In [ ]:
a_tf = tf.constant([1, 2, 3, 4])
a = a_tf.numpy()
print(a)
print(a.ndim)

[1 2 3 4]
1


4. 주어진 튜플 t = (5, 6, 7, 8)을 사용하여 numpy 배열, PyTorch 텐서, TensorFlow 텐서를 생성하는 코드를 작성하세요.

In [ ]:
t = (5, 6, 7, 8)
a = np.array(t)
a_t = torch.tensor(t)
a_tf = tf.constant(t)

print(a)
print(a_t)
print(a_tf)

[5 6 7 8]
tensor([5, 6, 7, 8])
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)


5. PyTorch 텐서 a_torch가 주어졌을 때, 이를 TensorFlow 텐서로 변환하는 코드를 작성하세요.

In [ ]:
a_torch = torch.tensor([1, 2, 3, 4])
a_tf = tf.constant(a_torch)
b_tf = tf.convert_to_tensor(a_torch)
print(a_tf)
print(b_tf)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


Numpy 배열 a_np를 생성하고, 이 배열을 사용하여 동일한 데이터를 가지지만 서로 다른 라이브러리(TensorFlow, PyTorch)의 Tensor 객체를 생성하는 코드를 작성하세요.

In [ ]:
a_np = np.arange(0, 6, 1)
a_t = torch.from_numpy(a_np)
a_tf = tf.convert_to_tensor(a_np)

print(a_t)
print(a_tf)

tensor([0, 1, 2, 3, 4, 5])
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)


다음 코드를 실행한 후의 a_np의 출력값은 무엇일까요?
```
t = (1, 2, 3, 4)
a_np = np.array(t)
a_torch = torch.tensor(a_np)
a_torch[2] = 777

print(a_np)
```

- [1 2 3 4]

다음 코드를 실행한 후 b_np의 출력값은?
```
t = (1, 2, 3, 4)
a_tf = tf.constant(t)
b_np = a_tf.numpy()
b_np[2] = 777

print(b_np)
```

- [1 2 777 4]

다음 코드를 실행한 후 a_torch와 b_torch의 출력값은?
```
t = (1, 2, 3, 4)
a_np = np.array(t)
b_torch = torch.from_numpy(a_np)
a_np[2] = 777

a_torch = torch.tensor(t)
print(a_torch)
print(b_torch)
```

- tensor([1, 2, 3, 4])
- tensor([1, 2, 777, 4])

### 다음 코드를 실행한 후, a_np, a_torch, (b_torch)의 결과를 예측하세요.
```
import numpy as np
import torch

t = (1, 2, 3, 4)
a_np = np.array(t)
a_torch = torch.tensor(a_np)
b_torch = torch.from_numpy(a_np)

b_torch[2] = 777
```

- a_np: [1 2 777 4]
- a_torch: tensor([1, 2, 3, 4])
- b_torch: tensor([1, 2, 777, 4])


```
import numpy as np
import torch

t = (5, 10, 15, 20)
a_np = np.array(t)
a_torch = torch.tensor(a_np)
b_torch = torch.from_numpy(a_np)

a_np[1] = 100

```

- a_np: [5 100 15 20]
- a_torch: tensor([5, 10, 15, 20])
- b_torch: tensor([5, 100, 15, 20])


```
import numpy as np
import torch

t = (0.1, 0.2, 0.3, 0.4)
a_np = np.array(t)
a_torch = torch.tensor(a_np)
b_torch = torch.from_numpy(a_np)

b_torch[0] = 999

```

- a_np: [999 0.2 0.3 0.4]
- a_torch: tensor([0.1, 0.2, 0.3, 0.4])
- b_torch: tensor([999, 0.2, 0.3, 0.4])

```
import numpy as np
import torch

t = [9, 8, 7, 6]
a_np = np.array(t)
a_torch = torch.tensor(a_np)
b_torch = torch.from_numpy(a_np)

a_torch[3] = 1000
```


- a_np: [9 8 7 6]
- a_torch: tensor([9, 8, 7, 1000])
- b_torch: tensor([9, 8, 7, 6])

```
import numpy as np
import torch

t = (11, 22, 33, 44)
a_np = np.array(t)
a_torch = torch.tensor(a_np)
b_torch = torch.from_numpy(a_np)

b_torch = torch.tensor([55, 66, 77, 88])
```

- a_np: [11 22 33 44]
- a_torch: tensor([11, 22, 33, 44])
- b_torch: tensor([55, 66, 77, 88])

```
import numpy as np
import torch

t = (2, 4, 6, 8)
a_torch = torch.tensor(t)
a_np = a_torch.numpy()

a_torch[1] = 100
a_np[2] = 999
```

In [47]:
import numpy as np
import torch

t = (2, 4, 6, 8)
a_torch = torch.tensor(t)
a_np = a_torch.numpy()

a_torch[1] = 100
a_np[2] = 999

tensor([  2, 100, 999,   8])

- a_np: [2 100 999 8]
- a_torch: tensor([2, 100, 999, 8])

```
import numpy as np
import torch

t = [5, 10, 15, 20]
a_torch = torch.tensor(t)
a_np = a_torch.numpy()

a_np[0] = 777
a_torch[3] = 888
```

- a_np: [777 10 15 888]
- a_torch: tensor([777, 10, 15, 888])

```
import numpy as np
import torch

t = (0.5, 1.0, 1.5, 2.0)
a_torch = torch.tensor(t)
a_np = a_torch.numpy()

a_torch[2] = 999
a_np[1] = 777

```

- a_np: [0.5, 777, 999, 2.0]
- a_torch: tensor([0.5, 777, 999, 2.0])

### 다음 코드를 실행한 후 a_np, a_tf, b_tf의 결과를 예측하세요

```
import numpy as np
import tensorflow as tf

t = [3, 6, 9, 12]
a_np = np.array(t)
a_tf = tf.constant(a_np)
b_tf = tf.convert_to_tensor(a_np)

a_np[2] = 999
```

- a_np: [3 6 999 12]
- a_tf: tf.Tensor([3 6 9 12])
- b_tf: tf.Tensor([3 6 9 12])

```
import numpy as np
import tensorflow as tf

t = [3, 6, 9, 12]
a_np = np.array(t)
a_tf = tf.constant(a_np)
a_np[2] = 999
b_tf = tf.convert_to_tensor(a_np)


```

- a_np: [3 6 999 12]
- a_tf: tf.Tensor([3 6 9 12])
- b_tf: tf.Tensor([3 6 999 12])

```
import numpy as np
import tensorflow as tf

t = [1.1, 2.2, 3.3, 4.4]
a_np = np.array(t)
a_tf = tf.constant(a_np)
b_tf = tf.convert_to_tensor(a_np)

b_tf[3] = 888
```

```
import numpy as np
import tensorflow as tf

t = [7, 14, 21, 28]
a_np = np.array(t)
a_tf = tf.constant(a_np)
b_tf = tf.convert_to_tensor(a_np)

a_tf = tf.constant([1, 2, 3, 4])

```

- a_np: [7 14 21 28]
- a_tf: tf.Tensor([1 2 3 4])
- b_tf: tf.Tensor([7 14 21 28])

```
import numpy as np
import tensorflow as tf

t = (10, 20, 30, 40)
a_np = np.array(t)
a_tf = tf.constant(a_np)
b_tf = tf.convert_to_tensor(a_np)

b_tf = tf.constant([50, 60, 70, 80])

```

- a_np: [10 20 30 40]
- a_tf: tf.Tensor([10 20 30 40])
- b_tf: tf.Tensor([50 60 70 80])