<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Practice/tensor-creation_and_checking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import torch
import numpy as np
import tensorflow as tf

# Tensor Creation

1. PyTorch를 사용하여 3x3 크기의 랜덤한 텐서를 생성하고 출력하세요.

In [2]:
t = torch.rand(3,3)
print(t)

tensor([[0.7804, 0.2516, 0.3044],
        [0.4548, 0.3764, 0.3498],
        [0.8972, 0.1118, 0.6326]])


2. NumPy를 사용하여 모든 값이 0인 크기가 (4, 2)인 행렬을 생성하고 출력하세요.

In [4]:
t = np.zeros((4,2))
print(t)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


3. TensorFlow를 사용하여 1에서 10까지의 숫자로 이루어진 1차원 텐서를 생성하고 출력하세요.

In [10]:
t = tf.linspace(1, 10, 10)
print(t)

tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float64)


In [13]:
t = tf.range(1, 11, 1)
print(t)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


4. PyTorch를 사용하여 2x2 크기의 단위 행렬(identity matrix)을 생성하고 출력하세요.

In [29]:
a_t = torch.eye(2)
print(a_t)

tensor([[1., 0.],
        [0., 1.]])


5. NumPy를 사용하여 3x3 크기의 모든 요소가 1인 행렬을 생성하고 출력하세요.

In [30]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


6. TensorFlow를 사용하여 4x4 크기의 모든 요소가 0인 행렬을 생성하고 출력하세요.

In [31]:
a_tf = tf.zeros((4,4))
print(a_tf)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


7. PyTorch를 사용하여 3차원의 크기가 (2, 3, 4)인 랜덤한 텐서를 생성하고 출력하세요.

In [33]:
a_t = torch.rand(24).reshape(2,3,4)
print(a_t)
print(a_t.shape)

tensor([[[0.2575, 0.3797, 0.9407, 0.3572],
         [0.6402, 0.2799, 0.1153, 0.5646],
         [0.4285, 0.6131, 0.1425, 0.9006]],

        [[0.9417, 0.5300, 0.8327, 0.1116],
         [0.6908, 0.5967, 0.3867, 0.8732],
         [0.7992, 0.7890, 0.0710, 0.2176]]])
torch.Size([2, 3, 4])


8. NumPy를 사용하여 1부터 10까지의 숫자로 이루어진 1차원 배열을 생성하고 출력하세요.

In [34]:
a = np.arange(1, 11, 1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


9. PyTorch를 사용하여 10부터 20까지의 숫자로 이루어진 1차원 텐서를 생성하고 출력하세요.

In [40]:
a_t = torch.arange(10, 21, 1)
print(a_t)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


10. TensorFlow를 사용하여 랜덤한 실수 값으로 이루어진 2x3x4 크기의 텐서를 생성하고 출력하세요.

In [47]:
a_tf = tf.random.uniform(shape=[2,3,4])
print(a_tf)

tf.Tensor(
[[[0.15724134 0.6619135  0.37365496 0.8280219 ]
  [0.26908815 0.44617045 0.661368   0.80773413]
  [0.7123344  0.7186307  0.28576016 0.25967038]]

 [[0.7079599  0.5665163  0.24847174 0.40549743]
  [0.8566592  0.658973   0.2818942  0.75252616]
  [0.48827994 0.08695817 0.24540794 0.4389367 ]]], shape=(2, 3, 4), dtype=float32)


In [48]:
a_tf = tf.random.normal((2,3,4))
print(a_tf)

tf.Tensor(
[[[-0.16741638 -0.0903293  -1.7839351  -0.2580345 ]
  [-0.69353133 -0.6378479  -0.4907138  -2.0854604 ]
  [ 0.348408    0.45687863 -0.38634628  1.3075079 ]]

 [[ 0.49305516  1.7685043  -0.49232447 -1.8886913 ]
  [ 0.35147825  0.4685747  -0.68841606 -0.8843067 ]
  [-1.1114802  -1.4839015   0.9483162  -2.3914757 ]]], shape=(2, 3, 4), dtype=float32)


# Tensor Understanding

1. 주어진 PyTorch 텐서의 모양(shape)과 데이터 타입(dtype)을 확인하세요.<br>
`a_t = torch.arange(0, 12, 1).reshape(3, 4)`

In [14]:
a_t = torch.arange(0, 12, 1).reshape(3, 4)
print(a_t.shape)
print(a_t.dtype)

torch.Size([3, 4])
torch.int64


2. NumPy 배열을 사용하여 만든 행렬의 차원(dimension) 수를 확인하세요.

In [15]:
a = np.arange(0, 12, 1).reshape(2, 2, 3)
print(a.ndim)

3


3. TensorFlow 텐서의 크기(size)를 계산하세요.

In [26]:
a_tf = tf.ones((2,3))
print(tf.size(a_tf))

tf.Tensor(6, shape=(), dtype=int32)
(2, 3)


4. PyTorch를 사용하여 모든 요소가 0이고 크기가 (3, 3)인 텐서를 생성하고, 그 텐서의 총 요소 수를 계산하세요.<br>
(did not covered.)

In [37]:
a_t = torch.zeros((3,3))
print(a_t.numel())

9


5. NumPy를 사용하여 크기가 (2, 4)이고 모든 요소가 5인 행렬을 생성하고, 해당 행렬의 데이터 타입을 확인하세요.

In [39]:
a = np.full((2, 4), 5)
print(a)
print(a.dtype)

[[5 5 5 5]
 [5 5 5 5]]
int64
