<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Practice/tensor-indexing_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 주어진 배열
arr = np.arange(27).reshape(3, 3, 3)

# slicing을 사용하여 아래 조건에 맞는 결과를 출력하세요.
# - 첫 번째 축에서 index가 1인 slice
# - 두 번째 축에서 index가 0부터 1까지의 slice
# - 세 번째 축에서 index가 2인 slice
print(arr)
print(arr[1, 0:2, 2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[11 14]
[11 14 17]


In [17]:
import torch

# 주어진 텐서
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Fancy Indexing을 사용하여 아래 조건에 맞는 결과를 출력하세요.
# - 세 번째 행과 첫 번째 행을 선택하여 출력
# - 두 번째 열과 세 번째 열을 선택하여 출력
f_indices = [[2, 0]]

print(tensor[f_indices])
print(tensor[:, 1:])

tensor([[7, 8, 9],
        [1, 2, 3]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


아래 코드의 빈칸을 채워서 주어진 NumPy 배열을 사용하여 인덱싱을 수행하고 결과를 출력하세요.

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[2, 1])
print('----------')
print(a[1])
print('----------')
print(a[:, 0])
print('----------')
print(a[1, 0:2])


- 8
- [4 5 6]
- [1 4 7]
- [4 5]

아래 코드의 빈칸을 채워서 주어진 PyTorch 텐서를 사용하여 인덱싱을 수행하고 결과를 출력하세요.
```
import torch

a_torch = torch.tensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

print(a_torch[0, 2])
print('----------')
print(a_torch[2])
print('----------')
print(a_torch[:, 0])
print('----------')
print(a_torch[1, 0:2])
```

- tensor(3)
- tensor([7, 8, 9])
- tensor([1, 4, 7])
- tensor([4, 5])

아래 코드의 빈칸을 채워서 주어진 TensorFlow 텐서를 사용하여 인덱싱을 수행하고 결과를 출력하세요.

```
import tensorflow as tf

a_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(a_tf[0, 2])
print('----------')
print(a_tf[2])
print('----------')
print(a_tf[:, 0])
print('----------')
print(a_tf[1, 0:2])
```


- tf.Tensor(3)
- tf.Tensor([7 8 9])
- tf.Tensor([1 4 7])
- tf.Tensor([4 5])

아래 주어진 NumPy 배열을 사용하여 인덱싱 및 슬라이싱을 수행한 결과를 예측하세요.
```
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[1]) # 결과: ?
print('----------')
print(a[:, 0:2]) # 결과: ?
```

- [4 5 6]
- [[1 2]<br>
   [4 5]<br>
   [7 8]]

In [21]:
import numpy as np

# 주어진 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Fancy Indexing을 사용하여 아래 조건에 맞는 결과를 출력하세요.
# - 첫 번째 행과 세 번째 행을 선택하여 출력
# - 두 번째 열과 세 번째 열을 선택하여 출력
print(arr[[0, 2]])
print(arr[:, [1, 2]])

[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [25]:
import numpy as np

# 주어진 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Fancy Indexing을 사용하여 아래 조건에 맞는 결과를 출력하세요.
# - 인덱스가 (0, 2), (1, 1), (2, 0)인 위치의 값을 선택하여 출력
print(arr[(0, 1, 2), (2, 1, 0)])

[3 5 7]


In [30]:
import numpy as np

# 주어진 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Fancy Indexing을 사용하여 아래 조건에 맞는 결과를 출력하세요.
# - 첫 번째 행과 두 번째 행에서 값을 선택하여 출력
# - 두 번째 열과 세 번째 열에서 값을 선택하여 출력
print(arr[0:2])
print(arr[0:2, 1:3])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


# Boolean Masking

In [33]:
import numpy as np

# 주어진 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Boolean Masking을 사용하여 아래 조건에 맞는 결과를 출력하세요.
# - 배열 arr에서 값이 5보다 큰 값들만 선택하여 출력
# - 배열 arr에서 짝수인 값들만 선택하여 출력
print(arr[arr>5])
print(arr[arr % 2 == 0])

[6 7 8 9]
[2 4 6 8]


In [40]:
import numpy as np

# 주어진 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Boolean Masking을 사용하여 아래 조건에 맞는 결과를 출력하세요.
# - 배열 arr에서 값이 3의 배수인 값들만 선택하여 출력
# - 배열 arr에서 값이 7 또는 9인 값들만 선택하여 출력
print(arr[arr % 3 == 0])
print(arr[(arr == 7) | (arr == 9)])
print(arr % 3 == 0)
print((arr == 7) | (arr == 9))

[3 6 9]
[7 9]
[[False False  True]
 [False False  True]
 [False False  True]]
[[False False False]
 [False False False]
 [ True False  True]]
