<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/02-filling_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor에 값 채우기

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


## zeros
- 행렬을 0으로 채움

In [4]:
# numpy
a = np.zeros((3,2))
print(a.dtype)
print(a, end="\n\n")

# pytorch
a_torch = torch.zeros((3,2))
print(a_torch.dtype)
print(a_torch, end="\n\n")

a_tf = tf.zeros(shape=(3,2))
print(a_tf.dtype)
print(a_tf)

float64
[[0. 0.]
 [0. 0.]
 [0. 0.]]

torch.float32
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

<dtype: 'float32'>
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


## ones
- 행렬을 1으로 채움

In [5]:
# numpy
a = np.ones((3,2))
print(a.dtype)
print(a, end="\n\n")

# pytorch
a_torch = torch.ones((3,2))
print(a_torch.dtype)
print(a_torch, end="\n\n")

# tensorflow
a_tf = tf.ones(shape=(3,2))
print(a_tf.dtype)
print(a_tf)

float64
[[1. 1.]
 [1. 1.]
 [1. 1.]]

torch.float32
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

<dtype: 'float32'>
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## full / fill
- 행렬을 특정 값으로 가득 채움

In [8]:
# numpy
a_np = np.full((1,3),255)
print(a_np.dtype)
print(a_np, end="\n\n")

# torch
a_torch = torch.full((1,3),255)
print(a_torch.dtype)
print(a_torch, end="\n\n")

# tensorflow
a_tf = tf.fill((1,3),255)
print(a_tf.dtype)
print(a_tf)

int64
[[255 255 255]]

torch.int64
tensor([[255, 255, 255]])

<dtype: 'int32'>
tf.Tensor([[255 255 255]], shape=(1, 3), dtype=int32)


## 원하는 값으로 행렬 채우기
- arange: 시작과 끝값을 설정하고 특정 값이 계속 더해지는 1차원 벡터 생성
- linspace: 시작과 끝값을 설정하고 특정 값으로 등분하는 1차원 벡터 샐성
- empty: 빈 값으로 행렬 생성
- eye: identity matrix 생성



### arange

In [9]:
print(range(0,10,1))
print(np.arange(0, 1, 0.1))
a = np.arange(0,24,2).reshape(3,4)
print(a.dtype)
print(a)

range(0, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
int64
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


### linspace

In [12]:
# numpy
a = np.linspace(1,5,6) # (시작, 끝, 등분)
print(a.dtype)
print(a, end='\n\n')

# pytorch
a_torch = torch.linspace(1,5,6)
print(a_torch.dtype)
print(a_torch, end='\n\n')

# tensorflow
a_tf = tf.linspace(1,5,6) # float32가 아닌 float64임을 주의.
print(a_tf.dtype)
b_tf = tf.dtypes.cast(a_tf, tf.float32) # 바꿔서 casting해주는 것이 좋음.
print(b_tf.dtype)
print(b_tf)

float64
[1.  1.8 2.6 3.4 4.2 5. ]

torch.float32
tensor([1.0000, 1.8000, 2.6000, 3.4000, 4.2000, 5.0000])

<dtype: 'float64'>
<dtype: 'float32'>
tf.Tensor([1.  1.8 2.6 3.4 4.2 5. ], shape=(6,), dtype=float32)


### empty / eye

In [13]:
# empty
# numpy
a = np.empty((4,2)) # 초기화를 안 하기 때문에 빠름.
print(a.dtype)
print(a, end='\n\n')

# pytorch
a_torch = torch.empty((4,2))
print(a_torch.dtype)
print(a_torch, end='\n\n')

# eye
a = np.eye(3) # identitiy matrix
print(a)

float64
[[5.06454545e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
torch.float32
tensor([[-5.9084e+18,  4.4923e-41],
        [ 3.8010e-06,  3.3450e-41],
        [ 1.6460e+19,  2.9423e+26],
        [ 0.0000e+00,  0.0000e+00]])
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
