<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/02-filling_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor에 값 채우기

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


- `zeros()`
- `ones()`
- `full() / fill()`
- `arange()`
- `linspace()`
- `empty()`
- `eye()`

## zeros
- 행렬을 0으로 채움

In [4]:
# numpy
a = np.zeros((3,2))
print(a.dtype)
print(a, end="\n\n")

# pytorch
a_torch = torch.zeros((3,2))
print(a_torch.dtype)
print(a_torch, end="\n\n")

# tensorflow
a_tf = tf.zeros(shape=(3,2))
print(a_tf.dtype)
print(a_tf)

float64
[[0. 0.]
 [0. 0.]
 [0. 0.]]

torch.float32
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

<dtype: 'float32'>
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


## ones
- 행렬을 1으로 채움

In [5]:
# numpy
a = np.ones((3,2))
print(a.dtype)
print(a, end="\n\n")

# pytorch
a_torch = torch.ones((3,2))
print(a_torch.dtype)
print(a_torch, end="\n\n")

# tensorflow
a_tf = tf.ones(shape=(3,2))
print(a_tf.dtype)
print(a_tf)

float64
[[1. 1.]
 [1. 1.]
 [1. 1.]]

torch.float32
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

<dtype: 'float32'>
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## full / fill
- 행렬을 특정 값으로 가득 채움
- numpy, pytorch는 `full()`, tensorflow는 `fill()`

In [6]:
# numpy
a_np = np.full((1,3),255)
print(a_np.dtype)
print(a_np, end="\n\n")

# torch
a_torch = torch.full((1,3),255)
print(a_torch.dtype)
print(a_torch, end="\n\n")

# tensorflow
a_tf = tf.fill((1,3),255)
print(a_tf.dtype)
print(a_tf)

int64
[[255 255 255]]

torch.int64
tensor([[255, 255, 255]])

<dtype: 'int32'>
tf.Tensor([[255 255 255]], shape=(1, 3), dtype=int32)


## 원하는 값으로 행렬 채우기
- arange: 시작과 끝값을 설정하고 특정 값이 계속 더해지는 1차원 벡터 생성
- linspace: 시작과 끝값을 설정하고 특정 값으로 등분하는 1차원 벡터 생성
- empty: 빈 값으로 행렬 생성
- eye: identity matrix 생성



### arange
끝값을 포함하지 않고 특정 값 더해 벡터 생성<br>
`arange(start, finish, add_val)`<br>
범위: [start, finish)
- tensorflow는 `arange()` 대신 `range()` 사용

In [8]:
print(range(0,10,1))

# numpy
print(np.arange(0, 1, 0.1))
a = np.arange(0,24,2).reshape(3,4)
print(a)

# torch
print(torch.arange(0, 10, 1))

# tensorflow
print(tf.range(0, 10, 1))

range(0, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


### linspace
끝값을 포함하여 벡터에 포함될 값의 개수를 지정해 등분하여 벡터 생성<br>
`arange(start, finish, num_val)`<br>
범위: [start, finish]



In [9]:
# numpy
a = np.linspace(1,5,6) # (시작, 끝, 등분)
print(a.dtype)
print(a, end='\n\n')

# pytorch
a_torch = torch.linspace(1,5,6)
print(a_torch.dtype)
print(a_torch, end='\n\n')

# tensorflow
a_tf = tf.linspace(1,5,6) # float32가 아닌 float64임을 주의.
print(a_tf.dtype)
b_tf = tf.dtypes.cast(a_tf, tf.float32) # 바꿔서 casting해주는 것이 좋음.
print(b_tf.dtype)
print(b_tf)

float64
[1.  1.8 2.6 3.4 4.2 5. ]

torch.float32
tensor([1.0000, 1.8000, 2.6000, 3.4000, 4.2000, 5.0000])

<dtype: 'float64'>
<dtype: 'float32'>
tf.Tensor([1.  1.8 2.6 3.4 4.2 5. ], shape=(6,), dtype=float32)


### empty
크기를 지정하여 빈 텐서 생성.
- 초기화를 하지 않기 때문에 속도가 빠름.
- tensorflow `tf.empty()` 지원 안 함.
- `tf.experimental.numpy.empty((4,2))`로 사용

In [14]:
# empty
# numpy
a = np.empty((4,2))
print(a.dtype)
print(a, end='\n\n')

# pytorch
a_torch = torch.empty((4,2))
print(a_torch.dtype)
print(a_torch, end='\n\n')

# tensorflow
# a_tf = tf.empty((4,2)) 지원 안 함
a_tf = tf.experimental.numpy.empty((4,2))
print(a_tf)

float64
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

torch.float32
tensor([[ 4.6581e-32,  4.4183e-41],
        [-1.4129e+36,  3.1028e-41],
        [ 4.4842e-44,  0.0000e+00],
        [ 6.7262e-44,  0.0000e+00]])

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float64)


### eye
대칭행렬 생성.
row와 col의 사이즈가 같은 행렬이기 때문에, 크기 하나만 인수로 받음.

In [16]:
# eye
# numpy
a = np.eye(3) # identitiy matrix
print(a)

# torch
a_t = torch.eye(3)
print(a_t)

# tensorflow
a_tf = tf.eye(3)
print(a_tf)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
