<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/06-vectorized_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectorized Operation
**scalar가 아닌 vector or matrix 전체에 대해 동일한 연산을 동시에 수행하는 방식.**
- homogeneous / contiguous tensor에서 모든 elements에 대해 같은 연산을 적용하여 기존 loop 연산에 비해 속도가 빠르며 간편한 연산자 사용.
- **코드 간결화**: 반복 루프를 사용하지 않고 vector/matrix 연산을 간결하게 표현.
- **효율성 향상**: SIMD를 활용하여 기존보다 훨씬 빠른 연산 수행.
- **메모리 사용량 증가**: multiple data를 한 번에 처리하므로 많은 메모리 사용을 요구함.
- numpy, pytorch, tensorflow 등에서 기본 제공.


In [ ]:
import numpy as np
import torch
import tensorflow as tf
import time

In [ ]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


## for loop과 vectorized operation의 차이


In [ ]:
def add_vectors(x, y):
  result = []
  for i in range(len(x)):
    result.append(x[i] + y[i])
  return result

x = np.arange(0, 1000, 1)
y = np.arange(0, 1000, 1)

start = time.time()
z = add_vectors(x, y)
end = time.time()

print(f"{end - start:.5f} sec")

0.00071 sec


In [ ]:
import numpy as np

x = np.arange(0, 1000, 1)
y = np.arange(0, 1000, 1)

start = time.time()
z = np.add(x, y)  # 벡터 덧셈
end = time.time()

print(f"{end - start:.5f} sec")

0.00014 sec


## 사칙연산

일반적인 파이썬 코드와 같음.
- Addition: +
- Multiplication: *
- Subtraction: -
- Division: /
- Negation: -

In [ ]:
# tensor 초기화
a = np.arange(6).reshape((3,2)).astype(np.float32)
b = np.ones((3,2),dtype=np.float32)
print(a.dtype, b.dtype)

a_t = torch.tensor(a).float()
b_t = torch.tensor(b).float()
print(a_t.dtype, b_t.dtype)

a_tf = tf.convert_to_tensor(a,dtype=tf.float32)
b_tf = tf.convert_to_tensor(b,dtype=tf.float32)
print(a_tf.dtype, b_tf.dtype)

float32 float32
torch.float32 torch.float32
<dtype: 'float32'> <dtype: 'float32'>


In [ ]:
# Addition

c = a + b
print(c)
c_t = a_t + b_t
print(c_t)
c_tf = a_tf + b_tf
print(c_tf)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [ ]:
# Multiplication

c = a * b
print(c)
c_t = a_t * b_t
print(c_t)
c_tf = a_tf * b_tf
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


In [ ]:
# Subtraction

c = a - b
print(c)
c_t = a_t - b_t
print(c_t)
c_tf = a_tf - b_tf
print(c_tf)

[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]
tensor([[-1.,  0.],
        [ 1.,  2.],
        [ 3.,  4.]])
tf.Tensor(
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]], shape=(3, 2), dtype=float32)


In [ ]:
# Division

c = a / b
print(c)
c_t = a_t / b_t
print(c_t)
c_tf = a_tf / b_tf
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


In [ ]:
# Negation

c = -a
print(c)
c_t = -a_t
print(c_t)
c_tf = -a_tf
print(c_tf)

[[-0. -1.]
 [-2. -3.]
 [-4. -5.]]
tensor([[-0., -1.],
        [-2., -3.],
        [-4., -5.]])
tf.Tensor(
[[-0. -1.]
 [-2. -3.]
 [-4. -5.]], shape=(3, 2), dtype=float32)


## Power & Exponentiation

### Power
$x^a$
- `a**2`
- `np.square(a)`
- `np.power(a, 2)`
- `torch.pow(a, 2)`
- `tf.pow(a, 2)`
- `pow()` 또는 `power()`의 경우 2 대신 다른 값을 넣으면 지수로 사용할 수 있음.

### Exponential
$e^x$&ensp;밑이 e인 지수
- `np.exp(a)`
- `torch.exp(a)`
- `tf.exp(a)`

$2^x$&ensp;밑이 2인 지수
- `np.exp2(a)`
- `torch.exp2(a)`
- `c_tf = tf.pow(2.,a_tf)`: exp 지원x

$a^x$&ensp;밑이 3 이상인 지수
- `np.power(3, a)`
- `torch.pow(3, a_t)`
- `tf.pow(3,a_tf)`




In [ ]:
# common operator

c = a**2
print(c)
c_t = a_t**2
print(c_t)
c_tf = a_tf**2
print(c_tf)

[[ 0.  1.]
 [ 4.  9.]
 [16. 25.]]
tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])
tf.Tensor(
[[ 0.  1.]
 [ 4.  9.]
 [16. 25.]], shape=(3, 2), dtype=float32)


In [ ]:
c = np.square(a)
print(c)
c = np.power(a,2)
print(c)
print('-------------')
c_t = torch.pow(a_t,2)
print(c_t)
c_tf = tf.pow(a_tf,2)
print(c_tf)

[[ 0.  1.]
 [ 4.  9.]
 [16. 25.]]
[[ 0.  1.]
 [ 4.  9.]
 [16. 25.]]
-------------
tensor([[ 0.,  1.],
        [ 4.,  9.],
        [16., 25.]])
tf.Tensor(
[[ 0.  1.]
 [ 4.  9.]
 [16. 25.]], shape=(3, 2), dtype=float32)


In [ ]:
# exponential

# 밑이 e인 지수
c = np.exp(a)
print(c)
c_t = torch.exp(a_t)
print(c_t)
c_tf = tf.exp(a_tf)
print(c_tf)

# 밑이 2인 지수
print()
c = np.exp2(a)
print(c)
c_t = torch.exp2(a_t)
print(c_t)
# c_tf = tf.exp2(a_tf) # not working
# print(c_tf)
c_tf = tf.pow(2.,a_tf)
print(c_tf)

# 밑이 3 이상인 지수
print()
c = np.power(3, a)
print(c)
c_t = torch.pow(3, a_t)
print(c_t)
c_tf = tf.pow(3,a_tf)
print(c_tf)

[[  1.          2.718282 ]
 [  7.3890557  20.085537 ]
 [ 54.59815   148.41316  ]]
tensor([[  1.0000,   2.7183],
        [  7.3891,  20.0855],
        [ 54.5981, 148.4132]])
tf.Tensor(
[[  1.          2.7182817]
 [  7.389056   20.085537 ]
 [ 54.59815   148.41316  ]], shape=(3, 2), dtype=float32)

[[ 1.  2.]
 [ 4.  8.]
 [16. 32.]]
tensor([[ 1.,  2.],
        [ 4.,  8.],
        [16., 32.]])
tf.Tensor(
[[ 1.  2.]
 [ 4.  8.]
 [16. 32.]], shape=(3, 2), dtype=float32)

[[  1.   3.]
 [  9.  27.]
 [ 81. 243.]]
tensor([[  1.,   3.],
        [  9.,  27.],
        [ 81., 243.]])
tf.Tensor(
[[  1.   3.]
 [  9.  27.]
 [ 81. 243.]], shape=(3, 2), dtype=float32)


## Log

$\ln$
- `np.log(a)`
- `torch.log(a)`
- `tf.math.log(a)`

$\log_2$
- `np.log2(a)`
- `torch.log2(a)`
- `tf.experimental.numpy.log2(a)`

$\log_{10}$
- `np.log10(a)`
- `torch.log10(a)`
- `tf.experimental.numpy.log10(a)`

In [ ]:
# 밑이 e인 로그
c = np.log(a)
print(c)
c_t = torch.log(a_t)
print(c_t)
c_tf = tf.math.log(a_tf)
print(c_tf)
print()

# 밑이 2인 로그
c = np.log2(a)
print(c)
c_t = torch.log2(a_t)
print(c_t)
# c_tf = tf.math.log2(a_tf) not working
# print(c_tf)
c_tf = tf.experimental.numpy.log2(a_tf)
print(c_tf)
print()

# 밑이 10인 로그
c = np.log10(a)
print(c)
c_t = torch.log10(a_t)
print(c_t)
# c_tf = tf.math.log10(a_tf) # not working
# print(c_tf)
c_tf = tf.experimental.numpy.log10(a_tf)
print(c_tf)
print()

[[     -inf 0.       ]
 [0.6931472 1.0986123]
 [1.3862944 1.609438 ]]
tensor([[  -inf, 0.0000],
        [0.6931, 1.0986],
        [1.3863, 1.6094]])
tf.Tensor(
[[     -inf 0.       ]
 [0.6931472 1.0986123]
 [1.3862944 1.609438 ]], shape=(3, 2), dtype=float32)

[[     -inf 0.       ]
 [1.        1.5849625]
 [2.        2.321928 ]]
tensor([[  -inf, 0.0000],
        [1.0000, 1.5850],
        [2.0000, 2.3219]])
tf.Tensor(
[[     -inf 0.       ]
 [1.        1.5849625]
 [2.        2.321928 ]], shape=(3, 2), dtype=float32)

[[      -inf 0.        ]
 [0.30103    0.47712123]
 [0.60206    0.69897   ]]
tensor([[  -inf, 0.0000],
        [0.3010, 0.4771],
        [0.6021, 0.6990]])
tf.Tensor(
[[      -inf 0.        ]
 [0.30102998 0.47712126]
 [0.60205996 0.69897   ]], shape=(3, 2), dtype=float32)



<ipython-input-27-bb1c3fd4992a>:2: RuntimeWarning: divide by zero encountered in log
  c = np.log(a)
<ipython-input-27-bb1c3fd4992a>:11: RuntimeWarning: divide by zero encountered in log2
  c = np.log2(a)
<ipython-input-27-bb1c3fd4992a>:22: RuntimeWarning: divide by zero encountered in log10
  c = np.log10(a)


## square root

In [ ]:
c = np.sqrt(a)
print(c)
c_t = torch.sqrt(a_t)
print(c_t)
c_tf = tf.sqrt(a_tf)
print(c_tf)

[[0.        1.       ]
 [1.4142135 1.7320508]
 [2.        2.236068 ]]
tensor([[0.0000, 1.0000],
        [1.4142, 1.7321],
        [2.0000, 2.2361]])
tf.Tensor(
[[0.        1.       ]
 [1.4142135 1.7320508]
 [2.        2.236068 ]], shape=(3, 2), dtype=float32)


## Absolute Value

Python의 built-in function인 abs도 사용가능하지만,

각 tensor가 속한 라이브러리의 abs를 사용하는게 효과적임.

In [ ]:
c = np.abs(a)           # 엄밀하게는 np.absolute
print(c)
c_t = torch.abs(a_t)
print(c_t)
c_tf = tf.abs(a_tf)
print(c_tf)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tf.Tensor(
[[0. 1.]
 [2. 3.]
 [4. 5.]], shape=(3, 2), dtype=float32)


## Relational Operation

\> , < , >= , <= , != , == 등.

결과값이 boolean tensor 임.

(아래에 기술한 boolean opeartion 과 함께 사용되어 특정 조건에 해당하는 elements를 찾는데 사용됨.)

In [ ]:
c = a > b
print(c)
c_t = a_t > b_t
print(c_t)
c_tf = a_tf > b_tf
print(c_tf)

[[False False]
 [ True  True]
 [ True  True]]
tensor([[False, False],
        [ True,  True],
        [ True,  True]])
tf.Tensor(
[[False False]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


## Trigonometric Operations
- 간단하게 `sin`, `cos`, `tan` 등을 사용할 수 있음.

In [ ]:
print("sine")
c = np.sin(a)
print(c)
c_t = torch.sin(a_t)
print(c_t)
c_tf = tf.sin(a_tf)
print(c_tf)

print("\ncosine")
c = np.cos(a)
print(c)
c_t = torch.cos(a_t)
print(c_t)
c_tf = tf.cos(a_tf)
print(c_tf)

print("\ntangent")
c = np.tan(a)
print(c)
c_t = torch.tan(a_t)
print(c_t)
c_tf = tf.tan(a_tf)
print(c_tf)

sine
[[ 0.         0.841471 ]
 [ 0.9092974  0.14112  ]
 [-0.7568025 -0.9589243]]
tensor([[ 0.0000,  0.8415],
        [ 0.9093,  0.1411],
        [-0.7568, -0.9589]])
tf.Tensor(
[[ 0.          0.84147096]
 [ 0.9092974   0.14112   ]
 [-0.7568025  -0.9589243 ]], shape=(3, 2), dtype=float32)

cosine
[[ 1.          0.5403023 ]
 [-0.4161468  -0.9899925 ]
 [-0.6536436   0.28366217]]
tensor([[ 1.0000,  0.5403],
        [-0.4161, -0.9900],
        [-0.6536,  0.2837]])
tf.Tensor(
[[ 1.          0.5403023 ]
 [-0.41614684 -0.9899925 ]
 [-0.6536436   0.2836622 ]], shape=(3, 2), dtype=float32)

tangent
[[ 0.          1.5574077 ]
 [-2.1850398  -0.14254655]
 [ 1.1578213  -3.380515  ]]
tensor([[ 0.0000,  1.5574],
        [-2.1850, -0.1425],
        [ 1.1578, -3.3805]])
tf.Tensor(
[[ 0.          1.5574077 ]
 [-2.1850398  -0.14254655]
 [ 1.1578213  -3.380515  ]], shape=(3, 2), dtype=float32)


## Aggregation
- 특정 축에 대해 수행
- axis: numpy, tensorflow
- dim: pytorch
- Nan이 있는 경우 에러 발생



In [ ]:
print("\nmax")
c = np.max(a)
print(c)
c_t = torch.max(a_t)
print(c_t)
c_tf = tf.reduce_max(a_tf)
print(c_tf)

print("\nmin")
c = np.min(a)
print(c)
c_t = torch.min(a_t)
print(c_t)
c_tf = tf.reduce_min(a_tf)
print(c_tf)

print("\nsum")
c = np.sum(a)
print(c)
c_t = torch.sum(a_t)
print(c_t)
c_tf = tf.reduce_sum(a_tf)
print(c_tf)

print('\nmean')
c = np.mean(a, axis=0)
print(c)
c_t = torch.mean(a_t, dim=0)
print(c_t)
c_tf = tf.reduce_mean(a_tf, axis=0)
print(c_tf)

print('\nmedian')
c = np.median(a, axis=0)
print(c)
c_t = torch.median(a_t, dim=0).values # indices도 구함.
print(c_t)
c_tf = tf.math.reduce_mean(a_tf, axis=0)
print(c_tf)


max
5.0
tensor(5.)
tf.Tensor(5.0, shape=(), dtype=float32)

min
0.0
tensor(0.)
tf.Tensor(0.0, shape=(), dtype=float32)

sum
15.0
tensor(15.)
tf.Tensor(15.0, shape=(), dtype=float32)

mean
[2. 3.]
tensor([2., 3.])
tf.Tensor([2. 3.], shape=(2,), dtype=float32)

median
[2. 3.]
tensor([2., 3.])
tf.Tensor([2. 3.], shape=(2,), dtype=float32)


## Boolean Operations

In [ ]:
bm0= [[False, False],
 [False,  True],
 [ True,  True]]
bm1= [[False, False],
 [False, False],
 [ True,  True]]


bm0 = a > 2.5
bm1 = a > 3.5
print('bm0=',bm0)
print('bm1=',bm1)
bm0_t = a_t > 2.5
bm1_t = a_t > 3.5
bm0_tf = a_tf > 2.5
bm1_tf = a_tf > 3.5

print('\nand')
c = bm0 & bm1 # and
print(c)
c_t = bm0_t & bm1_t
print(c_t)
c_tf = bm0_tf & bm1_tf
print(c_tf)

print('\nor')
c = bm0 | bm1 # or
print(c)
c_t = bm0_t | bm1_t
print(c_t)
c_tf = bm0_tf | bm1_tf
print(c_tf)

print('\nxor')
c = bm0 ^ bm1 # xor
print(c)
c_t = bm0_t ^ bm1_t
print(c_t)
c_tf = bm0_tf ^ bm1_tf
print(c_tf)


print('\nnot')
c = ~bm0 # not
print(c)
c_t = ~bm0_t
print(c_t)
c_tf = ~bm0_tf
print(c_tf)


bm0= [[False False]
 [False  True]
 [ True  True]]
bm1= [[False False]
 [False False]
 [ True  True]]

and
[[False False]
 [False False]
 [ True  True]]
tensor([[False, False],
        [False, False],
        [ True,  True]])
tf.Tensor(
[[False False]
 [False False]
 [ True  True]], shape=(3, 2), dtype=bool)

or
[[False False]
 [False  True]
 [ True  True]]
tensor([[False, False],
        [False,  True],
        [ True,  True]])
tf.Tensor(
[[False False]
 [False  True]
 [ True  True]], shape=(3, 2), dtype=bool)

xor
[[False False]
 [False  True]
 [False False]]
tensor([[False, False],
        [False,  True],
        [False, False]])
tf.Tensor(
[[False False]
 [False  True]
 [False False]], shape=(3, 2), dtype=bool)

not
[[ True  True]
 [ True False]
 [False False]]
tensor([[ True,  True],
        [ True, False],
        [False, False]])
tf.Tensor(
[[ True  True]
 [ True False]
 [False False]], shape=(3, 2), dtype=bool)
