<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/07-broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadcasting

차원이 맞지 않는 matrix 혹은 matrix와 scalar를 연산시킬 때 **차원 또는 길이를 확장시켜** 연산이 가능하도록 하는 기능.
- numpy, pytorch, tensorflow에서 같은 방식으로 동작.

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


## 차원의 수(ndim)가 같지 않은 경우

**적은 ndarray의 shape가 leading side쪽(shape에서 왼쪽)으로 1로 padding됨.**

- A의 shape가 (3,4,1) 이고, B의 shape가 (1,2)이면,
- B가 2차원(ndim=2)이므로 3차원(ndim=3)으로 늘어나고,
- leading side(왼쪽)로 1로 padding된 shape가 됨.

**B는 (1,2)에서 (1,1,2)이 됨.**



In [27]:
# numpy
a = np.ones((3,4,1))
b = np.ones((1,2))
print("a\n", a)
print("b\n", b)
c = a+b
print(c.shape, end='\n\n')

# torch
a_torch = torch.ones((3,4,1))
b_torch = torch.ones((2))
c_torch = a_torch + b_torch
print(c_torch.shape, end='\n\n')

# tensorflow
a_tf = tf.ones((3,4,1))
b_tf = tf.ones((2))
c_tf = a_tf + b_tf
print(c_tf.shape)

a
 [[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]]
b
 [[1. 1.]]
(3, 4, 2)

torch.Size([3, 4, 2])

(3, 4, 2)


## 차원의 수(ndim)은 같으나, shape이 일치하지 않는 경우

**ndarray 각각에서 shape가 1인 차원이 상대방의 해당하는 차원의 shape로 변경됨.**

A의 shape가 (3,4,1) 이고, B의 shape가 (1,1,2)이면
- A의 첫번째 차원의 shape수인 3에 맞춰 B의 첫번째 차원의 shape도 3이 됨.
- 두번째 차원의 경우, A의 4에 맞춰 B도 4로 늘어남.
- 세번째 차원의 경우 B의 2에 맞춰 A의 1이 2로 늘어남.

In [29]:
a = np.ones((3,4,1))
b = np.ones((1,1,2))
c = a+b
print(c.shape, end='\n\n')

(3, 4, 2)



# Broadcasting이 실패하는 경우
**ndim은 같고 shape이 일치하지 않는 위의 경우에서 어느 한 쪽 ndarray가 1이 아니면 실패.**

In [32]:
a = np.ones((3,4,1))
b = np.ones((1,2,2))
# c = a+b
# print(c.shape, end='\n\n') # 실패. 두 번째 차원을 맞출 수 없음

a = np.ones((3, 2))
b = np.arange(3)
# print(a+b) 실패: 차원을 맞출 수 없음

a = np.ones((3, 2))
b = np.arange(3).reshape(3,1) # 이렇게 하면 차원을 맞출 수 있음
print(a+b)



[[1. 1.]
 [2. 2.]
 [3. 3.]]


## PyTorch

In [ ]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)
print()

# matrix + scalar
m = torch.FloatTensor([[1,2]])
s = torch.FloatTensor([3])
print(m)
print(s)
print(m+s)
print()

# 2x1 matrix + 1x2 matrix
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1)
print(m2)
print(m1+m2)
