<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/Lecture-Deep_Learning/01-tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Manipulation

In [2]:
import numpy as np
import torch

In [9]:
for c in [np, torch]:
  print(c.__name__, c.__version__)

numpy 1.25.2
torch 2.2.1+cu121


# Tensor
- scalar: scalar
- vector: array of scalar
- matrix: array of vector
- 3d-tensor: array of matrix

# NumPy
## 1D Array with NumPy

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print()
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)
print()
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # Slicing
print('t[:2] t[:3].    = ', t[:2], t[:3]) # Slicing

[0. 1. 2. 3. 4. 5. 6.]

Rank  of t:  1
Shape of t:  (7,)

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[:3].    =  [0. 1.] [0. 1. 2.]


## 2D Array with NumPy

In [7]:
t = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print()
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]

Rank  of t:  2
Shape of t:  (4, 3)


## 3D Array with NumPy

In [8]:
t = np.array([[[1,2], [2,3]], [[3,4], [4,5]]])
print(t)
print()
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]

Rank  of t:  3
Shape of t:  (2, 2, 2)


# PyTorch
## 1D Array with PyTorch

In [10]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # Element
print(t[2:5], t[4:-1]) # Slicing
print(t[:2], t[3:]) # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [12]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10.,11.,12.]
                      ])
print(t)
print()

print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Tensor from np.array

In [16]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9,10,11]]])

t_torch1 = torch.FloatTensor(t)
print(t_torch1.shape)

t_torch2 = torch.from_numpy(t).float()
print(t_torch2.shape)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])


# Broadcasting

In [28]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)
print()

# matrix + scalar
m = torch.FloatTensor([[1,2]])
s = torch.FloatTensor([3])
print(m)
print(s)
print(m+s)
print()

# 2x1 matrix + 1x2 matrix
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1)
print(m2)
print(m1+m2)

tensor([[5., 5.]])

tensor([[1., 2.]])
tensor([3.])
tensor([[4., 5.]])

tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


## Multiplication & Matrix Multiplication

In [30]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('mul')
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.mul(m2))
print()

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('matmul')
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

mul
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])

matmul
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


## Mean

In [32]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [33]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max & Argmax

In [34]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

print(t.max())

print(t.max(dim=0))
print(t.max(dim=1))
print(t.max(dim=-1))

print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


# Squeeze & Unsqueeze

In [36]:
# Squeeze

t_torch = torch.FloatTensor([[0], [1], [2]])
print(t_torch)
print(t_torch.shape)
print(t_torch.squeeze())
print(t_torch.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [38]:
# Unsqueeze

t_torch = torch.Tensor([0,1,2])
print(t_torch)
print(t_torch.shape)
print(t_torch.unsqueeze(0))
print(t_torch.unsqueeze(0).shape)

print()
print(t_torch.view(1, -1))
print(t_torch.view(1, -1).shape)
print(t_torch.unsqueeze(1))
print(t_torch.unsqueeze(1).shape)
print(t_torch.unsqueeze(-1))
print(t_torch.unsqueeze(-1).shape)


tensor([0., 1., 2.])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type casting

In [40]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)

print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## concatenate
- 차원을 유지하면서 위아래/양옆으로 늘림

In [41]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])



## stacking
- 한 차원을 늘리면서 이어붙임.

In [43]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones & Zeros

In [44]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [45]:
x = torch.FloatTensor([[1,2], [3,4]])

print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
