<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/01-checking_size_ndim_shape_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checking size / ndim / shape / type
- ndim: dimension 개수
- shape: 몇 행, 몇 열인지 반환
- itemsize: 차지하는 byte 수
- size: 전체 원소의 개수
- dtype: data type
data type에서 (6)과 (6,)은 매우 다른 것임.
(6)은 integer, (6,)은 튜플.

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


## NumPy

In [3]:
t = (1,2,3,4,5,6)
a = np.array(t)
print(type(t))
print(type(a))
print(a.ndim)
print(a.shape)
print(a.itemsize) # byte 수
print(a.size)
print(a.dtype)

<class 'tuple'>
<class 'numpy.ndarray'>
1
(6,)
8
6
int64


In [4]:
a = np.array([1.,2.,3.])
print(a.dtype)
a = np.array([1.,2.,3.], dtype=int)
print(a.dtype)
a = np.array([1.,2.,3.], dtype=float)
print(a.dtype)

float64
int64
float64


## TensorFlow
- gpu기반 연산이기 때문에 int32와 float32를 사용.

In [7]:
tensor = tf.constant(t)
print(tf.rank(tensor)) # dimension 수 반환.
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
tensor

tf.Tensor(1, shape=(), dtype=int32)
1
(6,)
<dtype: 'int32'>


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

## PyTorch

In [5]:
p = torch.tensor(t)
print(p.ndim, type(p.ndim))
print(p.shape, type(p.shape))
print(p.itemsize, type(p.itemsize))
print(p.size, type(p.size()))
print(p.dtype, type(p.dtype))

1 <class 'int'>
torch.Size([6]) <class 'torch.Size'>
8 <class 'int'>
<built-in method size of Tensor object at 0x7e4f7efa3c90> <class 'torch.Size'>
torch.int64 <class 'torch.dtype'>


## dtype
- numpy: float64 / int64
- tensorflow: float32 / int32
- torch: float32 / int64

In [8]:
# 이건 기억을 해놓자
print(np.array([1.,2.,3.]).dtype)
print(np.array([1,2,3]).dtype)
print(tf.constant([1.,2.,3.]).dtype)
print(tf.constant([1,2,3]).dtype)
print(torch.tensor([1.,2.,3.]).dtype)
print(torch.tensor([1,2,3]).dtype)

float64
int64
<dtype: 'float32'>
<dtype: 'int32'>
torch.float32
torch.int64


In [9]:
# nested lists result in multi-dimensional arrays
a = np.array([range(i, i+3) for i in [2,4,6]]) # comprehension
print(a.ndim)
print(a.shape)
print(a.itemsize) # byte 수
print(a.size)
print(a.dtype)
a

2
(3, 3)
8
9
int64


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
tensor = tf.constant(a)
print(tf.rank(tensor))
print(tensor.ndim)
print(tensor.dtype)
tensor

tf.Tensor(2, shape=(), dtype=int32)
2
<dtype: 'int64'>


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])>