<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/04-changing_dtype_shape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# dtype, shape 변경

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
for c in [np, torch, tf]:
  print(c.__name__, c.__version__)

numpy 1.25.2
torch 2.2.1+cu121
tensorflow 2.15.0


In [4]:
# tensor 생성
t = (1,2,3,4)

a_np = np.array(t)
a_torch = torch.tensor(t)
a_tf = tf.constant(t)

## dtype 변경

**dtype: The data type of element**

바꾸는 원본 tensor인스턴스를 기반으로 원하는 dtype으로 구성된 새로운 tensor인스턴스가 생성됨 (연결X)

### numpy
dtype 이름만으로 사용 가능.
- `ndarray.astype(desired_dtype)`
  - ex) a_float = a_np.astype('float32')
- `np.desired_dtype(src_array)`
  - ex) a_int = np.int32(a_np)

### pytorch
torch.dtype 형식
- `torch.tensor.type(desired_dtype)`
  - ex) a_float = a_torch.type(torch.float64)
- `tensor.to(desired_dtype)`
  - ex) a_int = a_torch.to(torch.int32)

### tensorflow
tf.dtype 형식
- `tensorflow.dtypes.cast(src_tensor, desired_dtype)`
  - ex) a_float = tf.dtypes.casts(a_tf, tf.float64)

### NumPy

In [25]:
a = np.ones((3,3))
b = np.uint8(a)
c = a.astype('float32')
d = np.int32(a)
print(c)

print(id(a),a.dtype)
print(id(b),b.dtype)
print(id(c),c.dtype)
print(id(d),d.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
140324546677616 float64
140324546678768 uint8
140324512719440 float32
140324548060880 int32


In [22]:
a[1][1] = 0
print(a, end="\n\n")

# 영향x
print(b)
print(c)
print(d)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Torch
(type이 float32이면 tensor 출력시 dtype을 따로 출력하지 않음.)

In [6]:
print(a_torch.dtype)
print(a_torch.to(dtype = torch.float32)) # to: dtype을 어딘가로 보냄.
print(a_torch.dtype) # 연결x

torch.int64
tensor([1., 2., 3., 4.])
torch.int64


In [14]:
a_torch = torch.rand(3,4)
b_torch = a_torch.to(torch.uint8) # 보통 데이터를 gpu 또는 cpu로 옮길 때 사용. 형 변환이 필요하기 때문에 함께 쓰임.
c_torch = a_torch.type(torch.float64)

print(a_torch)
print(b_torch)
print(c_torch, end="\n\n")
print(id(a_torch), a_torch.dtype)
print(id(b_torch), b_torch.dtype)
print(id(c_torch), c_torch.dtype)

b_torch[0,1] = 9
c_torch[0,0] = 1000
print()
print("b_torch: \n", b_torch)
print("c_torch: \n", c_torch)
print("a_torch: \n", a_torch) # b_torch와 c_torch의 값을 바꿔도 a_torch의 값이 변하지 않음.

tensor([[0.9889, 0.7115, 0.1673, 0.6618],
        [0.4739, 0.6860, 0.3276, 0.4921],
        [0.6148, 0.0571, 0.5319, 0.7147]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([[0.9889, 0.7115, 0.1673, 0.6618],
        [0.4739, 0.6860, 0.3276, 0.4921],
        [0.6148, 0.0571, 0.5319, 0.7147]], dtype=torch.float64)

140324551670768 torch.float32
140324836316384 torch.uint8
140324551727584 torch.float64

b_torch: 
 tensor([[0, 9, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
c_torch: 
 tensor([[1.0000e+03, 7.1151e-01, 1.6735e-01, 6.6179e-01],
        [4.7392e-01, 6.8599e-01, 3.2756e-01, 4.9210e-01],
        [6.1477e-01, 5.7141e-02, 5.3190e-01, 7.1466e-01]], dtype=torch.float64)
a_torch: 
 tensor([[0.9889, 0.7115, 0.1673, 0.6618],
        [0.4739, 0.6860, 0.3276, 0.4921],
        [0.6148, 0.0571, 0.5319, 0.7147]])


### TensorFlow

In [17]:
a_tf = tf.random.uniform(shape=(3,4))
c_tf = tf.dtypes.cast(a_tf,tf.float64)
print(a_tf)
print(c_tf)
print(id(a_tf), a_tf.dtype)
print(id(c_tf), c_tf.dtype)

tf.Tensor(
[[0.48520315 0.7671863  0.5304713  0.9550866 ]
 [0.16791809 0.13852668 0.94590735 0.0984906 ]
 [0.1073997  0.76407945 0.77132523 0.10747445]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0.48520315 0.76718628 0.53047132 0.95508659]
 [0.16791809 0.13852668 0.94590735 0.0984906 ]
 [0.1073997  0.76407945 0.77132523 0.10747445]], shape=(3, 4), dtype=float64)
140324815894336 <dtype: 'float32'>
140324815893456 <dtype: 'float64'>


## Shape 변경

- shape는 tensor의 각 축의 크기를 나타내는 sequence type의 인스턴스임.
- 즉, tensor의 크기와 형태를 나타냄.
- desired_shape은 튜플 형태로.
- 메모리가 contiguous해야 view를 만들 수 있음.
- transpose는 행렬을 바꿔놓기 때문에 일정하게 쭉 올라가던 메모리에서 순서가 꼬이게 됨. <br>is_contiguous 사용하면 인접한지 확인할 수 있음.


### numpy
같은 행렬에서 reshape로 얻은 행렬의 경우 서로에게 영향을 미침.
- `numpy.reshape(src_ndarray, desired_shape)`
- `numpy.array.reshape(desired_shape)`

### pytorch
같은 행렬에서 reshape로 얻은 행렬의 경우 서로에게 영향을 미침.
- `torch.reshape(src_tensor, desired_shape)`
- `torch.tensor.reshape(desired_shape)`

### tensorflow
reshape로 얻어도 영향 없음.<br>
src_tensor.reshape(desired_shape) 방식은 작동X.
- `tensorflow.reshape(src_tensor, desired_shape)`





### numpy

In [16]:
a = np.arange(0,10,1) # [ s : e : step_size ]
b = a.reshape((2,5))
print(a.shape,id(a))
print(b.shape,id(b))
c = np.reshape(a,(5,2))
print(c.shape,id(c), end="\n\n")

c[0,0] = 1000
# 같은 행렬에서 reshape로 얻은 행렬의 경우 서로에게 영향을 미침.
print(a)
print(b)
print(c)

(10,) 140324551552592
(2, 5) 140324551719792
(5, 2) 140324549838960

[1000    1    2    3    4    5    6    7    8    9]
[[1000    1    2    3    4]
 [   5    6    7    8    9]]
[[1000    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]]


### pytorch

In [29]:
a_torch = torch.arange(0,10,1)
b_torch = a_torch.reshape((2,5))
c_torch = torch.reshape(a_torch,(5,2))

print(a_torch.shape,id(a_torch))
print(b_torch.shape,id(b_torch))
print(c_torch.shape,id(c_torch), end="\n\n")

c_torch[0,0] = 1000
# 같은 행렬에서 reshape로 얻은 행렬의 경우 서로에게 영향을 미침.
print(a_torch)
print(b_torch)
print(c_torch)

torch.Size([10]) 140324551668768
torch.Size([2, 5]) 140324551659888
torch.Size([5, 2]) 140324548612944

tensor([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[1000,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([[1000,    1],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])


### tensorflow

In [23]:
a_tensor = tf.range(0,10,1)
b_tensor = tf.reshape(a_tensor,(2,5))
# b_tensor = a_tensor.reshape((2,5)) # not working
print(a_tensor.shape,id(a_tensor))
print(b_tensor.shape,id(b_tensor))

c_tensor = tf.reshape(a_tensor,(5,2))
print(c_tensor.shape,id(c_tensor), end="\n\n")

# 변경하고 싶은 위치와 값을 정의
indices = tf.constant([[0, 0]]) # (2, 2) 위치를 변경하고자 함
updates = tf.constant([999]) # 해당 위치에 넣고 싶은 값

# 업데이트 적용
c_tensor = tf.tensor_scatter_nd_update(c_tensor, indices, updates)
# 값을 바꾸어도 영향 없음.
print(a_tensor)
print(b_tensor)
print(c_tensor)

(10,) 140324512597616
(2, 5) 140324514566688
(5, 2) 140324514565632

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[999   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]], shape=(5, 2), dtype=int32)
