<a href="https://colab.research.google.com/github/9-coding/PyTorch/blob/main/11-tensor_max_min.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Find maximum and minimum from tensor

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
for c in [np,torch,tf]:
  print(c.__version__)

1.25.2
2.2.1+cu121
2.15.0


In [6]:
rng = np.random.default_rng(seed=23)
ori = rng.random((3,2)).astype(np.float32)
print(ori)

a_np = ori.copy()
a_torch = torch.tensor(ori)
a_tf = tf.Variable(ori)

[[0.69393307 0.6414582 ]
 [0.12864423 0.11370805]
 [0.6533455  0.8534571 ]]


## NumPy
- np.max 와 np.min 함수를 이용하여 최대, 최소인 값을 구함.
- 특정 축을 axis parameter로 지정하여 구할 수 있음 (결과는 해당 axis가 1이 됨.)
- np.argmax 와 np.argmin 함수를 이용하여 최대, 최소인 값의 index를 반환함.

In [25]:
print("max")
print(np.max(a_np)) # 전체
print(np.max(a_np, 0)) # row
print(np.max(a_np, 1)) # column

print("\nmin")
print(np.min(a_np)) # 전체
print(np.min(a_np, 0)) # row
print(np.min(a_np, 1)) # column

print("\nargmax")
print(np.argmax(a_np)) # 전체
print(np.argmax(a_np, 0)) # row
print(np.argmax(a_np, 1)) # column

print("\nargmin")
print(np.argmin(a_np)) # 전체
print(np.argmin(a_np, 0)) # row
print(np.argmin(a_np, 1)) # column

max
0.8534571
[0.69393307 0.8534571 ]
[0.69393307 0.12864423 0.8534571 ]

min
0.11370805
[0.12864423 0.11370805]
[0.6414582  0.11370805 0.6533455 ]

argmax
5
[0 2]
[0 0 1]

argmin
3
[1 1]
[1 1 0]


## PyTorch

`torch.max`와 `torch.min` 함수를 사용하여 최대값과 최소값을 구함.

- 특정 축을 `dim` parameter로 지정하여 구할 수 있음.
- 특정 축을 지정할 경우, `torch.max`와 `torch.min`은 indices를 같이 반환함.
- `torch.argmax` 와 `torch.argmin` 함수를 이용하여 최대, 최소값의 indices를 반환함.

In [26]:
print("max")
print(torch.max(a_torch)) # 축을 지정하지 않으면 값만 반환
print(torch.max(a_torch, 0)) # row
print(torch.max(a_torch, 1)) # column

print("\nmin")
print(torch.min(a_torch)) # 축을 지정하지 않으면 값만 반환
print(torch.min(a_torch, 0)) # row
print(torch.min(a_torch, 1)) # column

print("\nargmax")
print(torch.argmax(a_torch)) # 축을 지정하지 않으면 값만 반환
print(torch.argmax(a_torch, 0)) # row
print(torch.argmax(a_torch, 1)) # column

print("\nargmin")
print(torch.argmin(a_torch)) # 축을 지정하지 않으면 값만 반환
print(torch.argmin(a_torch, 0)) # row
print(torch.argmin(a_torch, 1)) # column

max
tensor(0.8535)
torch.return_types.max(
values=tensor([0.6939, 0.8535]),
indices=tensor([0, 2]))
torch.return_types.max(
values=tensor([0.6939, 0.1286, 0.8535]),
indices=tensor([0, 0, 1]))

min
tensor(0.1137)
torch.return_types.min(
values=tensor([0.1286, 0.1137]),
indices=tensor([1, 1]))
torch.return_types.min(
values=tensor([0.6415, 0.1137, 0.6533]),
indices=tensor([1, 1, 0]))

argmax
tensor(5)
tensor([0, 2])
tensor([0, 0, 1])

argmin
tensor(3)
tensor([1, 1])
tensor([1, 1, 0])


## TensorFlow

`tf.reduce_max`와 `tf.reduce_min` 함수를 사용하여 최대값과 최소값을 구함.

- 특정 축을 따라 구할 경우엔, `axis` parameter로 지정.
- torch.argmax 와 torch.argmin 함수를 이용하여 최대, 최소값의 indices를 반환함.

In [28]:
print("max")
print(tf.reduce_max(a_tf)) # 전체
print(tf.reduce_max(a_tf, 0))
print(tf.reduce_max(a_tf, 1))

print("\nmin")
print(tf.reduce_min(a_tf))
print(tf.reduce_min(a_tf, 0))
print(tf.reduce_min(a_tf, 1))

print("\nargmax")
print(tf.argmax(a_tf))
print(tf.argmax(a_tf, 0))
print(tf.argmax(a_tf, 1))

print("\nargmin")
print(tf.argmin(a_tf))
print(tf.argmin(a_tf, 0))
print(tf.argmin(a_tf, 1))

max
tf.Tensor(0.8534571, shape=(), dtype=float32)
tf.Tensor([0.69393307 0.8534571 ], shape=(2,), dtype=float32)
tf.Tensor([0.69393307 0.12864423 0.8534571 ], shape=(3,), dtype=float32)

min
tf.Tensor(0.11370805, shape=(), dtype=float32)
tf.Tensor([0.12864423 0.11370805], shape=(2,), dtype=float32)
tf.Tensor([0.6414582  0.11370805 0.6533455 ], shape=(3,), dtype=float32)

argmax
tf.Tensor([0 2], shape=(2,), dtype=int64)
tf.Tensor([0 2], shape=(2,), dtype=int64)
tf.Tensor([0 0 1], shape=(3,), dtype=int64)

argmin
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor([1 1 0], shape=(3,), dtype=int64)


<hr>

In [30]:
a_np = rng.random((2,2,3)).astype(np.float32)
a_np

array([[[0.20177913, 0.21801864, 0.7165846 ],
        [0.47069967, 0.41522193, 0.3491478 ]],

       [[0.06385376, 0.45466617, 0.3014533 ],
        [0.38907674, 0.5402978 , 0.6835897 ]]], dtype=float32)

In [31]:
a = torch.tensor(a_np)
m = torch.max(a,2)
print(m[0].shape)
print(m[1].shape)
m

torch.Size([2, 2])
torch.Size([2, 2])


torch.return_types.max(
values=tensor([[0.7166, 0.4707],
        [0.4547, 0.6836]]),
indices=tensor([[2, 0],
        [1, 2]]))

In [32]:
m = torch.max(a,1)
print(m[0].shape, m[1].shape)
m

torch.Size([2, 3]) torch.Size([2, 3])


torch.return_types.max(
values=tensor([[0.4707, 0.4152, 0.7166],
        [0.3891, 0.5403, 0.6836]]),
indices=tensor([[1, 1, 0],
        [1, 1, 1]]))

In [33]:
a_p = torch.permute(a, [0,2,1])
a_p

tensor([[[0.2018, 0.4707],
         [0.2180, 0.4152],
         [0.7166, 0.3491]],

        [[0.0639, 0.3891],
         [0.4547, 0.5403],
         [0.3015, 0.6836]]])